In [2]:
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / "src"))

os.chdir(PROJECT_ROOT)

print("Working directory:", Path.cwd())
print("Source directory:", PROJECT_ROOT / "src")

Working directory: /Users/camillecu/Downloads/KUL/llm_project/llm_project2026
Source directory: /Users/camillecu/Downloads/KUL/llm_project/llm_project2026/src

In [ ]:
import json
from dotenv import load_dotenv
from src.data_ingestion import fetch_data, normalize_example, chunk_text, load_to_db

In [ ]:
# testing fetch_data function
load_dotenv()

ticker = "AAPL"  # user provides only this
data = fetch_data(ticker)
data

In [ ]:
# store the data in a local file for reuse
# Path("data/transcripts").mkdir(parents=True, exist_ok=True) # create the directory if it doesn't exist

raw_doc_id = f"{data.get('symbol')}_{data.get('year')}Q{data.get('quarter')}"

raw_path = f"data/transcripts/{raw_doc_id}.json"

with open(raw_path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

In [4]:
def load_local_transcripts():
    transcripts = []
    for path in Path("data/transcripts").glob("*.json"):
        with open(path) as f:
            transcripts.append(json.load(f))
    return transcripts

In [7]:
transcripts = load_local_transcripts()
print(transcripts[0])

{'symbol': 'AAPL', 'year': 2026, 'quarter': 3, 'date': '2026-07-30T00:00:00.000Z', 'content': 'Suhasini Chandramouli: Good afternoon, welcome to the Apple Q3 fiscal year 2026 earnings conference call. My name is Suhasini Chandramouli, Director of Investor Relations. Today\'s call is being recorded. Speaking first today is Apple CEO Tim Cook, followed by CFO Kevan Parekh. Also joining us on today\'s call is incoming CEO John Ternus. After the prepared remarks, we\'ll open the call to questions from analysts. Please note that some of the information you\'ll hear during our discussion today will consist of forward-looking statements, including, without limitation, those regarding revenue, gross margin, operating expenses, other income and expense, taxes, and future business outlook. These statements involve risks and uncertainties that may cause actual results or trends to differ materially from our forecast, including risks related to the potential impact to the company\'s business and results of operations from macroeconomic conditions, tariffs and other measures, and legal and regulatory proceedings. For more information, please refer to the risk factors discussed in Apple\'s most recently filed reports on Form 10-Q and Form 10-K, and the Form 8-K filed with the SEC today, along with the associated press release. Additional information will also be in our report on Form 10-Q for the quarter ended June 27, 2026, to be filed tomorrow, and in other reports and filings we make with the SEC. Apple assumes no obligation to update any forward-looking statements which speak only as of the date they are made. I\'d now like to turn the call over to Tim for introductory remarks.\n\nTim Cook: Thank you, Suhasini. Good afternoon, everyone, thanks for joining the call. Today, Apple is pleased to report $109.4 billion in revenue, up 16% from a year ago and a June quarter record. We were able to achieve this despite supply constraints and sequential foreign exchange headwinds. We continue to see enormous customer enthusiasm for our most popular lineup ever, with iPhone revenue growing 22% from a year ago to reach a June quarter record. We saw so much excitement around the best Mac lineup we\'ve ever had, growing a strong 29% to achieve a June quarter revenue record. Services also set a June quarter record with $30.7 billion in revenue. We achieved June quarter revenue records in every geographic segment. We were pleased to see strength across the board with June quarter records in the U.S., Latin America, Western Europe, India, China Mainland, Japan, and Southeast Asia. We also achieved June quarter revenue records in both developed and emerging markets and saw double-digit growth in most emerging markets. This year\'s WWDC was a wonderful showcase of our latest innovations. We were tremendously excited to unveil the all-new Siri AI, a completely reimagined version of Siri that is profoundly capable, deeply personal, and integrated seamlessly across our platforms. We\'ve been absolutely thrilled by the response from people who\'ve been using Siri AI in the developer and public betas. The reviews from early users have been phenomenal, it\'s been so wonderful to hear from people who are excited about the capabilities we\'ve built. It underscores our philosophy that building AI that is private and based on personal context can change how users find information and get things done with our products in a way that truly enriches their lives. We really couldn\'t be more excited about it, we are feeling incredibly enthusiastic about the impact it\'s going to have. At WWDC, we also announced new tools to help parents keep kids safe online, we were pleased by the overwhelmingly positive reaction. New child safety features like Ask to Browse and Time Allowances will help parents encourage kids to develop healthy digital habits. These new tools integrate guidance from leading clinical and child development research, including the American Academy of Pediatrics. Our goal is to make it easier for parents to manage what their children see, who they interact with, and how and when they can use their devices. We\'re looking forward to bringing these new capabilities to users this fall, in addition to amazing new updates across our operating systems. Let me turn to the results for the quarter, beginning with iPhone. iPhone revenue for the June quarter was $54.3 billion, up 22% from a year ago. We achieved June quarter records in every geographic segment and set a June quarter record for upgraders. According to IDC, we gained share globally during the quarter. As I\'ve said before, this is the most powerful and most popular iPhone lineup we\'ve ever had. More people are relying on iPhone every day for AI, powered by the outstanding performance of A19 and A19 Pro. Across the lineup, iPhone continues to deliver the performance, battery life, durability, and camera capabilities that people count on every day. Whether it\'s the extraordinary camera system of iPhone 17 Pro and Pro Max, the remarkably thin design of iPhone Air, the balanced performance and durability of iPhone 17, or the exceptional value of iPhone 17e, there\'s an iPhone for every customer. Mac delivered its best June quarter yet with $10.4 billion in revenue, growing an impressive 29% from a year ago despite significant supply constraints. This revenue growth was driven by the incredible strength of our latest lineup with MacBook Pro and the all-new MacBook Neo. According to IDC, we gained share globally. We also set a June quarter revenue record in developed markets and an all-time record in emerging markets with particular strength in Greater China, where we had an all-time revenue record. In addition, we achieved all-time records for upgraders and customers new to Mac. With the power of Apple silicon, the Mac lineup delivers outstanding power-efficient performance, massive memory bandwidth, and next-level AI capabilities. Mac continues to be the ultimate AI powerhouse, excelling at high throughput, on-device inference, and creation across a broad range of AI workloads. We\'re seeing customers increasingly put those capabilities to work, from using Mac mini as a powerful platform for agentic AI to deploying clusters of Mac Studio systems to run frontier class models locally. Across the lineup, customers continue to embrace the Mac family. MacBook Neo has been especially popular with its distinctive design and excellent value resonating with customers around the world, we\'re continuing to work hard to meet demand. MacBook Air, the world\'s most popular laptop, continues to deliver the portability and performance customers love with M5. MacBook Pro, powered by M5 Pro and M5 Max, remains a go-to choice for professionals tackling the most demanding AI development and creative workflows. In iPad, revenue was $6.2 billion for the June quarter. iPad continues to be the ultimate go-anywhere, do anything device for students, entrepreneurs, and creators of all kinds, thanks to its incredible power, portability, and versatility. The addition of M4 to iPad Air has made it even more capable, delivering a significant performance boost for everything from personal productivity and immersive learning to advanced creative workflows. Together with the remarkable performance of iPad Pro, the amazing value and versatility of iPad, and the ultra-portable iPad mini, we\'re offering customers our strongest iPad lineup ever. Revenue for wearables, home, and accessories was $7.9 billion, up 6% from a year ago. We grew in every geographic segment and achieved a June quarter record for upgraders for Apple Watch. Our Apple Watch lineup brings together the most comprehensive set of health and fitness features we\'ve ever had. We\'re delivering useful features backed by research to enable users to better understand their health and well-being. It\'s gratifying to receive almost daily reminders of the meaningful impact Apple\'s health innovations are having for users all over the world, changing, even saving lives. Meanwhile, we continue raising the bar across our AirPods lineup, whether it\'s the immersive listening experience of AirPods Pro 3 or the premium listening experience and exceptional active noise cancellation of AirPods Max 2. With live translation powered by Apple Intelligence, people are crossing language barriers and connecting like never before. As I mentioned earlier, we\'re excited about the work we\'re doing on the next generation of Apple Intelligence, including Siri AI and the AI features we\'re developing across our platforms. These experiences are intuitive and useful, while also deeply integrated in a way that\'s personal and private with the latest models running on-device and on servers using private cloud compute. We began laying the groundwork for users to have the best possible experience with AI when we introduced the Neural Engine in 2017. Ever since then, we\'ve innovated and invested deliberately in silicon, systems, and scalable unified memory architecture designed with AI at their core. What sets Apple apart is the unique combination of massive unified memory bandwidth, industry-leading power-efficient performance, and deep on-device intelligence, all built around the customer experience from the ground up. The result is that Apple has created the world\'s best hardware to experience AI, whether using Apple Intelligence, including Siri AI, or third-party offerings. That\'s why developers and researchers are increasingly using Apple devices to build ever more advanced tools and models. Turning to services, revenue was $30.7 billion, a June quarter revenue record and up 12% from a year ago, despite significant sequential foreign exchange headwinds. We also set an all-time revenue record in developed markets and a June quarter record in emerging markets. Apple TV continues to leave audiences spellbound with new releases like "Widow\'s Bay" and "Cape Fear," alongside returning favorites like "Silo" and "Sugar." Next week, we\'re excited that "Ted Lasso" is back for its fourth season. It was wonderful to see Apple TV earn the industry\'s top honors, adding Tony Awards this year to its Emmy, Grammy, and Oscar wins. We reached that milestone faster than any streamer in history. We\'re also looking forward to this year\'s Emmy Awards, where Apple has landed a record 89 nominations, leading all networks in both the major drama and comedy series categories, with three Outstanding Drama Series nominations and three Outstanding Comedy Series nominations. "Widow\'s Bay" also stands out as the year\'s most nominated new program, earning 19 Emmy nominations. In the six and a half years since launch, Apple TV has earned more than 850 wins and nearly 3,800 nominations. In time for the World Cup, we expanded Apple Sports to include more than 170 countries and regions worldwide and made it easier than ever for fans to follow every moment of the tournament, from the opening game to the final whistle. At the same time, we\'re halfway through an unforgettable year of F1, and Apple TV subscribers have been tuning in all season to follow their favorite drivers and teams. In retail, we were pleased to announce Apple Upgrade this week for customers in the U.S. Apple Upgrade is a new hardware leasing program launched in partnership with Klarna and makes it even easier for customers to get their hands on Apple\'s latest products with a plan that\'s right for them. In all of our work, we\'re thoughtful and intentional in how we show up for our users and across our communities. That means innovating to protect user privacy with the next generation of Apple Intelligence, or helping parents keep kids safe, as I mentioned earlier. In honor of Global Accessibility Awareness Day, we unveiled new features to help users get more out of the products they use every day. New intelligent capabilities are coming to VoiceOver, Magnifier, Voice Control, and Accessibility Reader to make them more useful and intuitive. We\'re also using on-device speech recognition to generate subtitles for video content without captions. Apple Vision Pro is adding a feature for power wheelchair users to control drive systems using just their eyes. All of these features were born out of Apple\'s long-standing commitment to ensuring that the benefits of technology are shared with everyone. As we continue to develop new capabilities for users around the world, we\'re also doing our part to invest in innovation close to home. Last year, we made a $600 billion commitment to the U.S. over four years, and now, as we said before, we plan to reinvest the tariff refunds we\'ve received into the U.S. We\'re pleased with the progress we\'ve already made advancing the American supply chain. Earlier this month, Apple announced a new agreement with Broadcom to design and produce custom silicon components and cutting-edge wireless connectivity technologies. The new multi-year agreement with Broadcom, which is part of Apple\'s American Manufacturing Program, is expected to exceed $30 billion. This marks our largest-ever American manufacturing program commitment. It\'s also an important step forward in our work to build an end-to-end silicon supply chain here in the U.S. We\'re excited for the upcoming opening of the Apple Advanced Manufacturing Center in Houston. The center is located in a facility where we currently assemble advanced AI servers. Later this year, we\'ll make Mac mini there, too. The center will teach students, supplier employees, and business of all sizes the same innovative processes we use to make our products. The goal is to empower American manufacturers to take their work to the next level and strengthen the entire advanced manufacturing ecosystem. We have an exciting fall ahead and an incredible future beyond. Our roadmap is phenomenal, and we are so excited about the way Siri AI will enrich our users\' lives. Throughout all of it, we will remain guided by our North Star: building the best products and services to enable people to do magical things. It\'s a special privilege to be part of people\'s lives in lasting and meaningful ways, helping them to create, connect, and experience the world around them. I couldn\'t be more excited to watch our phenomenal story of innovation continue to unfold, and I\'ve never been more confident that the best is yet to come. With that, I\'ll turn it over to Kevan.\n\nKevan Parekh: Thanks, Tim, good afternoon, everyone. Here\'s a quick rundown of our key financial metrics. Our revenue of $109.4 billion was up 16% year-over-year, a June quarter revenue record. We saw strong performance around the world, with double-digit growth in every geographic segment despite supply constraints. Products revenue was $78.7 billion, up 18% year-over-year, driven by double-digit growth on iPhone and Mac, both of which set new June quarter records. Our installed base of over two and a half billion active devices has reached another all-time high across all major product categories and geographic segments. Services revenue was $30.7 billion, up 12% year-over-year. We set revenue records in every services category, including all-time records in cloud services and payment services. Company gross margin was 50.1%, up 80 basis points sequentially. This included a benefit from tariff refunds, which had a favorable impact of approximately two percentage points. When you remove this favorable impact, we would have been at the midpoint of the guidance range we provided last quarter. Products gross margin was 40.1%, up 140 basis points sequentially. This also included a benefit from the tariff refunds I just mentioned, which had a favorable impact of over two and a half percentage points. Services gross margin was 75.6%, down 110 basis points sequentially, driven by a different mix. Operating expenses came in at $19.1 billion, up 23% year-over-year, driven by investments in R&D. Net income was $29.8 billion. Diluted earnings per share was $2.02, up 29% year-over-year, and included $0.11 of favorable impact from tariff refunds. Operating cash flow was very strong at $34.4 billion. All three of these metrics set June quarter records, even when excluding the tariff refund benefit. I\'m going to provide some more details for each of our revenue categories. iPhone revenue was $54.3 billion, up 22% year-over-year, driven by the iPhone 17 family. We grew double digits in the vast majority of markets we track and reached June quarter revenue records across both developed and emerging markets. The iPhone active install base grew to an all-time high and set a June quarter record for upgraders. According to a recent survey from Worldpanel, iPhone was the top-selling model in the U.S., urban China, the U.K., France, Australia, and Japan. We were thrilled with the response to the iPhone 17 family. Customer satisfaction in the U.S. was recently measured at 99% by 451 Research. Mac revenue was $10.4 billion, up 29% year-over-year, a new June quarter record, driven by the strength of MacBook Neo and MacBook Pro. We grew in both developed and emerging markets, with strong double-digit growth in markets like Latin America, India, and Southeast Asia. The customer reception to MacBook Neo has been incredible. We continue to attract new customers to the product around the world. As Tim mentioned, Mac had its best quarter ever for customers new to the Mac and for upgraders worldwide, including in the U.S., China Mainland, and India. In the U.S., customer satisfaction for Mac was recently measured at 95%. iPad revenue was $6.2 billion, down 6% year-over-year, driven by the continued difficult compare against the launch of the A16-powered iPad in the prior year. At the same time, the iPad install base reached a new all-time high, and over half of the customers who purchased an iPad were new to the product. 451 Research recently measured customer satisfaction at 98% in the U.S. Wearables, home, and accessories revenue was $7.9 billion, up 6% year-over-year, driven by strength in wearables and accessories, and we saw growth in both developed and emerging markets. The wearables install base reached a new all-time high. We set a June quarter record for upgraders on Apple Watch, and over half the customers purchasing an Apple Watch during the quarter were new to the product. In the U.S., customer satisfaction on Apple Watch was reported at 95%. Our services revenue reached a June quarter record of $30.7 billion, up 12% year-over-year, despite significant sequential FX headwinds. For the total services business, we saw double-digit growth in the vast majority of markets we track. We set records in every category, with June quarter records in advertising, App Store, AppleCare, Apple Music, and Apple TV+, as well as all-time records in cloud services and payment services. We are optimistic about the long-term future of our services business. With our large install base of over two and a half billion active devices, we have an incredibly strong foundation for growth opportunities. Our services continue to attract more customers, and we have now surpassed one and a half billion in paid subscriptions. Both transacting and paid accounts reached new all-time highs in the quarter, with double-digit growth for both in emerging markets. We continue to improve and expand our services offerings, from powerful updates to Creator Studio to exciting new features we\'re bringing to services later this year, like splitting bills with Apple Cash using visual intelligence. Turning now to enterprise and education. Organizations are using the Apple platform to drive AI innovation and empower the next generation of students. Starting with enterprise, Morgan Stanley has deployed over 20,000 iPhone 17 devices globally as part of a shift from employee-owned to corporate-owned devices for liability and security. More companies are choosing Mac for on-device AI advantages, includin

In [ ]:
# testing normalize_example and chunk_text functions
normalized_transcript = normalize_example(transcripts[0])
chunks = chunk_text(normalized_transcript["text"], chunk_size=1000, overlap=150)

print(normalized_transcript["doc_id"])
print(normalized_transcript["metadata"])
print(len(chunks))
print(chunks[0][:300])

AAPL_2026Q3
{'source': 'roic.ai', 'symbol': 'AAPL', 'year': 2026, 'quarter': 3, 'date': '2026-07-30T00:00:00.000Z'}
59
Suhasini Chandramouli: Good afternoon, welcome to the Apple Q3 fiscal year 2026 earnings conference call. My name is Suhasini Chandramouli, Director of Investor Relations. Today's call is being recorded. Speaking first today is Apple CEO Tim Cook, followed by CFO Kevan Parekh. Also joining us on tod

In [ ]:
# testing embed_chunks function
from src.data_ingestion import embed_chunks



chunks = [
    "Apple reported strong revenue growth in the quarter.",
    "The company discussed tariff risks and margin pressure."
]

vectors = embed_chunks(chunks)
len(vectors), len(vectors[0])  # should return (2, 768) for Gemini text-embedding-004

/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3048, in run_cell
    result = self._run_cell(
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3103, in _run_cell
    result = runner(coro)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3308, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3490, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/cv/bbbq9ykj0jg6pt6c7tx5_vjh0000gn/T/ipykernel_41713/3624329625.py", line 1, in <module>
    from src.ingestion.data_ingestion import embed_chunks
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/src/ingestion/data_ingestion.py", line 7, in <module>
    from sentence_transformers import SentenceTransformer
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/sentence_transformers/__init__.py", line 10, in <module>
    from sentence_transformers.backend import (
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/sentence_transformers/backend/__init__.py", line 3, in <module>
    from .load import load_onnx_model, load_openvino_model
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/sentence_transformers/backend/load.py", line 7, in <module>
    from transformers.configuration_utils import PretrainedConfig
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/transformers/__init__.py", line 27, in <module>
    from . import dependency_versions_check
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/transformers/utils/__init__.py", line 24, in <module>
    from .auto_docstring import (
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/transformers/utils/auto_docstring.py", line 30, in <module>
    from .generic import ModelOutput
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/transformers/utils/generic.py", line 51, in <module>
    import torch
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/google/auth/__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/google/oauth2/__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)

(2, 384)

In [ ]:
# create the database and table if they don't exist
# this chunk of code is no longer needed (below one in used)
import os
import psycopg
from pgvector.psycopg import register_vector
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.environ["PG_CONN_STR"]  # e.g. postgresql://raguser:ragpass@localhost:5432/ragdb


# 1. Connect and create extension
with psycopg.connect(DATABASE_URL) as conn:
    with conn.cursor() as cur:
        cur.execute("CREATE EXTENSION IF NOT EXISTS vector;")

# 2. Reconnect, register vector, and create table + indexes
conn = psycopg.connect(DATABASE_URL)
register_vector(conn)

sql = """
CREATE TABLE IF NOT EXISTS earnings_chunks (
    id SERIAL PRIMARY KEY,
    doc_id TEXT NOT NULL,
    chunk_index INT NOT NULL,
    text TEXT NOT NULL,
    embedding vector(384),      
    symbol TEXT,
    year INT,
    quarter INT,
    date DATE,
    source TEXT
);

CREATE INDEX IF NOT EXISTS earnings_chunks_symbol_year_quarter_idx
    ON earnings_chunks (symbol, year, quarter);

CREATE INDEX IF NOT EXISTS earnings_chunks_embedding_idx
    ON earnings_chunks
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);
"""

with conn:
    with conn.cursor() as cur:
        cur.execute(sql)

conn.close()

In [16]:
import os
import psycopg
from dotenv import load_dotenv

load_dotenv()
conn = psycopg.connect(os.environ["PG_CONN_STR"])

conn.execute("DROP TABLE IF EXISTS earnings_chunks")

conn.execute("""
    CREATE TABLE earnings_chunks (
        id SERIAL PRIMARY KEY,
        doc_id TEXT NOT NULL,
        chunk_index INT NOT NULL,
        text TEXT NOT NULL,
        embedding vector(384),
        symbol TEXT,
        year INT,
        quarter INT,
        date DATE,
        source TEXT
    )
""")

conn.execute("""
    CREATE INDEX earnings_chunks_symbol_year_quarter_idx
        ON earnings_chunks (symbol, year, quarter)
""")

conn.execute("""
    CREATE INDEX earnings_chunks_embedding_idx
        ON earnings_chunks
        USING ivfflat (embedding vector_cosine_ops)
        WITH (lists = 100)
""")

conn.commit()
conn.close()

In [17]:
import os
import psycopg
from dotenv import load_dotenv

load_dotenv()
conn = psycopg.connect(os.environ["PG_CONN_STR"])

row = conn.execute("""
    SELECT atttypmod
    FROM pg_attribute
    JOIN pg_class ON pg_attribute.attrelid = pg_class.oid
    WHERE pg_class.relname = 'earnings_chunks'
      AND pg_attribute.attname = 'embedding'
""").fetchone()

print(row)
conn.close()

(384,)

In [18]:
import os
import psycopg
from dotenv import load_dotenv

load_dotenv()
conn = psycopg.connect(os.environ["PG_CONN_STR"])

# Check table exists
exists = conn.execute("""
    SELECT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_name = 'earnings_chunks'
    )
""").fetchone()[0]

print("table exists:", exists)

# Check columns
cols = conn.execute("""
    SELECT column_name, data_type, udt_name
    FROM information_schema.columns
    WHERE table_name = 'earnings_chunks'
    ORDER BY ordinal_position
""").fetchall()

print(cols)

conn.close()

table exists: True
[('id', 'integer', 'int4'), ('doc_id', 'text', 'text'), ('chunk_index', 'integer', 'int4'), ('text', 'text', 'text'), ('embedding', 'USER-DEFINED', 'vector'), ('symbol', 'text', 'text'), ('year', 'integer', 'int4'), ('quarter', 'integer', 'int4'), ('date', 'date', 'date'), ('source', 'text', 'text')]

In [19]:
import os
import psycopg
from dotenv import load_dotenv

load_dotenv()
conn = psycopg.connect(os.environ["PG_CONN_STR"])

idx = conn.execute("""
    SELECT indexname, indexdef
    FROM pg_indexes
    WHERE tablename = 'earnings_chunks'
""").fetchall()

for row in idx:
    print(row)

conn.close()

('earnings_chunks_pkey', 'CREATE UNIQUE INDEX earnings_chunks_pkey ON public.earnings_chunks USING btree (id)')
('earnings_chunks_symbol_year_quarter_idx', 'CREATE INDEX earnings_chunks_symbol_year_quarter_idx ON public.earnings_chunks USING btree (symbol, year, quarter)')
('earnings_chunks_embedding_idx', "CREATE INDEX earnings_chunks_embedding_idx ON public.earnings_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists='100')")

In [20]:
# testing load_to_db function
conn_str = os.getenv("PG_CONN_STR")

load_dotenv()

ticker = "AAPL"  # user provides only this
data = fetch_data(ticker)
normalized = normalize_example(data)
chunks = chunk_text(normalized["text"], chunk_size=1000, overlap=150)
vectors = embed_chunks(chunks)


load_to_db(conn_str, normalized, chunks, vectors)

In [26]:
# inspect the database to see if the data was inserted correctly
conn = psycopg.connect(os.environ["PG_CONN_STR"])
rows = conn.execute("""
    SELECT doc_id, chunk_index, symbol, year, quarter, date, source, left(text, 200), embedding AS preview
    FROM earnings_chunks
    ORDER BY id DESC
    LIMIT 5
""").fetchall()

for row in rows:
    print(row)

conn.close()

('AAPL_2026Q3', 58, 'AAPL', 2026, 3, datetime.date(2026, 7, 30), 'roic.ai', "A replay of today's call will be available on Apple Podcasts and at apple.com/investor. Thanks again for joining us today.\n\nOperator: Once again, this does conclude today's conference. We do appreciat", '[-0.08065571,-0.0404788,0.05397811,-0.031422887,-0.008527379,0.014938744,0.068862855,-0.06492392,0.04101206,-0.013517394,-0.037250794,0.058744628,-0.08489764,0.019458495,0.028475476,-0.006853469,-0.006487692,0.0010341099,-0.05547202,0.033583954,-0.04154746,0.009528695,0.025305636,0.01884141,0.056528866,-0.07673517,-0.039796617,0.027868357,0.0031666688,-0.060354542,-0.044352118,0.05203672,0.0399886,0.06328956,0.022529406,-0.038238823,0.022010135,-0.004928428,-0.018332468,0.029698672,-0.022803752,-0.059537124,-0.013038505,0.013600304,-0.030460862,-0.055073876,-0.050960056,-0.02679131,0.1395337,0.09443193,0.0034861057,-0.013494012,0.045434486,-0.07807061,0.056156553,0.18975306,0.046982594,0.022791222,0.08529018,0.021308819,0.042957317,-0.068322815,0.016753588,0.098197125,0.01902063,0.047051203,-0.03201293,0.042651027,-0.03382135,-0.022954121,0.025655389,-0.021500956,0.026465919,-0.05746272,0.026242709,0.07462285,-0.013345018,-0.0669663,-0.032488983,0.028242528,-0.018874142,-0.0814422,-0.059531596,-0.05390418,0.024077326,-0.0129011795,0.013738687,0.0072155143,0.039489757,-0.011269329,-0.10127749,0.033712097,0.024508884,0.0036144785,-0.012512025,-0.04777816,-0.03878623,-0.024096023,-0.031382713,0.045510314,0.013590609,0.05466384,-0.017514154,-0.037800346,-0.021839835,-0.0892492,-0.06369499,0.032652613,0.04566501,0.050806127,0.0053871097,0.023973737,0.02003981,0.051862802,0.020549795,0.032357514,-0.0084262015,0.011530639,0.046293736,-0.055240862,-0.002617171,0.011557426,-0.047471087,-0.045632884,0.03736949,-0.037663184,0.105284356,-2.7686828e-33,-0.010301589,-0.033142205,0.024666376,0.02664895,0.036027543,-0.06819495,0.012428637,0.0026984494,-0.062796384,-0.12134691,0.0031438689,0.055497136,0.046081133,-0.041178398,-0.10808759,-0.039766084,-0.021079991,0.01886902,-0.023824757,0.036748126,0.014509913,0.06561533,-0.04465166,-0.005153937,0.028310172,-0.018682709,0.09411527,-0.05733928,0.12702794,0.03002346,-0.0813345,-0.019523175,-0.057113636,-0.018045316,0.044025857,0.085862234,0.011576332,0.022866657,-0.057961922,-0.030814886,-0.021801276,-0.014954037,-0.06594897,-0.09105592,0.035064556,-0.08305422,-0.04283258,0.06265793,0.076507404,0.0005661811,-0.048406627,0.05114941,-0.005110681,-0.016321236,-0.013955278,-0.09520119,-0.03488677,0.010370793,-0.0021409455,0.06600401,0.049021035,0.01735174,-0.06034687,-0.009660514,-0.12966362,0.09867511,-0.03251358,-0.0067570414,-0.052443177,0.06648711,0.010114127,-0.00431491,-0.023230303,-0.051517613,-0.042035483,-0.017269557,-0.028626708,-0.0011471051,0.046524357,0.053517334,0.016862884,-0.06744115,-0.03573031,0.008003332,0.054601315,0.07183183,0.029870173,-0.07159012,-0.038674112,0.08514274,-0.08594362,0.080589384,0.03207741,0.03805278,-0.02681298,-1.3839035e-33,0.0057839807,-0.007166141,-0.05503112,0.034467682,-0.061596762,0.0038334737,-0.058869507,0.0983194,-0.10579176,-0.07729745,0.04782486,0.033942357,0.011651299,-0.008585804,-0.04185207,-0.0756361,-0.04615364,-0.040351618,-0.023458844,0.03409389,0.059177697,-0.0482307,0.06863342,0.046169534,-0.016094469,0.0065842066,0.054399457,0.0560361,0.012227521,-0.086285606,-0.031944957,-0.0747793,-0.052349087,0.0610485,0.12161244,0.07261436,0.113733284,0.0037413489,0.007184248,-0.028329825,0.027538976,-0.013828501,-0.020520762,-0.0176242,0.015487508,-0.008282889,-0.004449705,0.062220007,-0.042339604,-0.041545782,0.030773979,-0.0066762343,-0.03566822,0.0020313167,-0.087714784,0.044195514,0.033704747,-0.036645465,0.03320821,0.011641071,-0.09534258,-0.0012450273,0.011871309,-0.070242,0.053268276,0.010355447,-0.001770391,-0.0022751256,-0.012205986,0.067535765,0.032874163,0.030948564,-0.09771264,-0.05881191,0.0033251143,0.07438852,0.00076904905,-0.044724844,-0.037137713,0.02188017,0.0043136803,0.10390909,0.06744279,0.034845058,0.060641903,0.08156302,0.08332851,0.027583273,-0.018298265,0.08908816,-0.068775184,-0.04341947,0.011054159,-0.009230629,-0.059481706,-3.6161207e-08,-0.03950917,0.078961864,0.039855935,0.0046282383,0.013681757,-0.03178523,0.022698967,-0.11542799,-0.003148695,-0.051592994,0.028198514,-0.00029030145,-0.13028994,0.06227484,0.003850599,-0.009744897,-0.04934794,-0.022580788,-0.0135763455,-0.070525266,0.021501573,-0.023699684,0.09319609,0.026740113,-0.032076746,0.08910989,-0.07408837,0.06110637,0.010625623,-0.038184922,-0.08924279,0.037862763,-0.07026533,-0.051258765,-0.022427253,-0.12849316,-0.0025635937,0.002446318,0.07094522,-0.057136305,-0.06760762,-0.06770815,0.012180113,0.026943447,0.028849768,0.01045887,0.0127357235,-0.07070916,-0.032219913,0.001804246,-0.041769832,-0.057012815,0.041566107,0.043111384,-0.011926969,0.07359252,0.018921053,-0.10703874,0.0037916545,0.0244161,0.05630128,0.021319548,-0.053164717,0.059250925]')
('AAPL_2026Q3', 57, 'AAPL', 2026, 3, datetime.date(2026, 7, 30), 'roic.ai', ' and some favorable mix. We are seeing the same dynamics when you go from the 48.1% that we printed in the June quarter to the 46.5% midpoint you referenced of our range without the tariff refund impa', '[0.009111248,0.0023894513,0.050804798,0.034502864,0.05726392,0.043053925,0.0024379257,0.0933794,-0.014570034,-0.018834926,-0.009990481,0.104613565,-0.015207814,-0.060107082,0.021923577,-0.007938692,0.029800149,-0.05229051,-0.05924134,0.05054154,0.033009138,-0.027768,-0.031712066,0.030155182,0.07433695,0.07821292,-0.036524653,-0.013186753,0.0064706425,-0.059980545,-0.058690544,0.14675894,-0.030952813,-0.003281,-0.005839569,-0.013609736,-0.0031694153,-0.017674949,0.004170261,-0.056017745,-0.0113515565,0.066261105,-0.07022845,0.111468785,-0.02088089,-0.009726096,0.041644964,0.014063889,-0.020207558,0.058424782,0.018227369,0.097620904,-0.03961117,-0.047063828,0.0049351137,0.08321417,0.07511154,0.0028986915,0.022624802,0.037957888,-0.08722328,-0.13388625,0.014691279,-0.024379391,-0.014907123,-0.10459974,-0.011289022,-0.06545782,-0.07814226,-0.001819547,0.014246098,-0.012671097,0.057980772,-0.07460793,0.032200653,0.030484803,0.077499345,-0.0047238753,0.049258932,-0.05110808,0.021472791,-0.015569177,0.025161052,-0.032354075,0.03990571,-0.08088383,0.08315546,-0.022749059,-0.01778422,-0.04219996,0.11256107,0.02501446,0.026585517,0.011734123,0.02408171,0.053767767,-0.033878084,0.042842936,0.04214034,0.016936269,0.121024996,0.12115623,-0.034048356,-0.05140032,-0.0592645,-0.051065747,-0.019680317,0.01789273,-0.03817884,0.013664763,0.009087848,0.015750945,-0.011469915,0.04490049,-0.011365711,-0.05481837,0.009146083,-0.07865819,0.115109704,-0.019755054,0.008155464,0.06710191,-0.019442912,0.06815106,-0.09181754,0.02699618,0.006795156,2.933942e-33,-0.07747007,0.03183029,-0.038754974,-0.06853832,-0.03869806,-0.065672584,0.025088346,0.042423707,-0.008392673,0.0052277087,-0.04967092,0.08870925,0.0120900655,0.031317364,-0.000502958,-0.13374473,-0.07673801,0.019271318,0.07220481,0.01577737,-0.019682538,0.03494328,0.015927132,-0.04660351,-0.0068598012,-0.0036470264,-0.006028544,-0.02559889,-0.0122791305,0.012596348,-0.029029615,0.05563897,-0.008743622,-0.06368523,-0.029180871,-0.007637108,0.038754977,-0.04980283,-0.075803585,-0.083668746,-0.049948223,0.12923102,-0.0147754,-0.081575416,-0.07696769,-0.028179822,0.032687537,0.017310208,0.02892883,0.025303867,-0.10905802,0.027512146,-0.010651598,-0.03676845,-0.015679166,-0.008434878,-0.020538492,-0.09274329,0.04798856,0.07997731,0.02835055,0.06127583,0.0022208132,0.033059098,-0.07774019,0.11824425,0.010641177,0.040859304,-0.11614847,0.06547066,0.0077699525,-0.017904952,0.026888294,-0.015313422,0.008562542,-0.0116387885,0.02204856,0.012765047,0.013220182,-0.08679089,-0.0117908735,-0.061153118,0.033087965,-0.051311437,0.00704879,0.014602094,0.06869966,0.008174387,-0.004764889,0.03322684,0.030951992,-0.037045665,0.056539945,0.046776824,-0.04795772,-4.7039295e-33,-0.031239448,0.063792996,0.010606501,0.04374043,-0.083731726,-0.022980478,0.024620432,0.10720678,-0.03827899,-0.02447741,-0.01495866,0.05329034,-0.022314183,0.045846697,-0.11465721,-0.03274405,-0.01397894,-0.01719816,0.022618476,-0.067503005,0.056648843,0.042664666,-0.0094277775,0.063266486,-0.04894848,0.052682534,-0.024494495,-0.017294345,0.044293817,-0.05562042,-0.029406162,-0.026879357,0.012048736,0.022839447,0.00869535,-0.000928094,0.0020737438,0.029621355,0.016179677,0.035687424,0.027512943,0.040191308,-0.019943608,-0.010645968,0.06333432,0.031658053,-0.01964043,0.042215478,0.07357142,-0.033335637,-0.012667135,0.033047345,-0.05108864,0.0183373,-0.11955508,0.0085189445,0.05905649,-0.016883343,-0.01629345,-0.044687036,-0.03343677,0.02006981,-0.022921592,-0.14629613,0.056264076,0.0065931757,0.035457693,-0.13258944,0.062496595,0.020453343,-0.013847042,-0.0038538699,-0.071827576,-0.0782591,-0.0042868885,0.057720546,0.035938773,-0.021945419,-0.031690326,0.033775967,0.009318513,0.09980006,-0.012826461,0.018346118,-0.007261587,0.054133516,-0.013216529,-0.04375313,-0.013445836,0.049274605,-0.075709544,-0.036212374,-0.0535678,0.006982292,-0.05086722,-5.8308686e-08,-0.04660182,0.006935435,0.035570245,0.08636095,0.019801198,-0.061189253,-0.024584616,0.06511667,0.016465338,0.041672993,0.059464425,0.0043212445,-0.08943504,-0.0009327733,-0.016886987,0.046266638,-0.045068853,0.02255381,0.024450656,-0.061064847,-0.031320162,0.07520332,0.043722887,0.022364445,0.013118216,0.0023438828,0.0059382278,0.14047362,0.0010806493,-0.059589792,-0.06771583,0.026868021,-0.04381524,-0.05727312,-0.029306512,-0.059164867,-0.035119843,-0.010568273,0.07366478,0.013721217,-0.0692827,-0.0757736,-0.0128471,0.041313104,0.029116511,-0.03958471,-0.13111128,-0.016129622,0.00819527,-0.05981402,0.040361065,0.037057437,-0.04037085,0.051575296,0.071543284,-0.003876906,-0.07006609,-0.06883546,-0.03502864,0.013353579,0.057638556,-0.113512434,-0.1294619,0.040108014]')
('AAPL_2026Q3', 56, 'AAPL', 2026, 3, datetime.date(2026, 7, 30), 'roic.ai', "ving that sequential moderation? It does seem a bit more atypical than your normal sort of years.\n\nKevan Parekh: Yeah, Samik, that's a good question. Let me walk through kind of what's impacting our g", '[0.038536508,-0.055347946,0.027344456,0.07681714,0.05532365,0.0726753,-0.011038058,0.067564785,-0.015286145,-0.00734182,-0.013258328,0.093157455,-0.015581126,-0.048959974,0.0183188,-0.034074742,0.015526877,-0.024748217,-0.010084189,0.031486724,0.022009734,-0.04730441,-0.021442551,-0.011869376,0.017637305,0.102799684,-0.038122635,-0.008269526,0.02515172,-0.09708477,-0.0080198925,0.15264492,0.0071573462,-0.019436596,0.010358092,0.01688531,0.0120594,0.026963774,-0.032242574,-0.035377868,-0.08172663,0.05461807,-0.033644926,0.029249607,-0.009524697,-0.030022012,0.08087041,0.00079789024,-0.03220515,0.012561758,-0.0044909567,0.06014687,-0.024432061,-0.031761553,-0.010768648,0.08118944,0.040504992,0.010763928,-0.013490744,0.03141362,-0.105155446,-0.087327786,-0.045757048,-0.048399504,0.008810261,-0.01606264,0.03319015,-0.056463473,-0.05913195,0.06472294,0.0027596937,-0.03772659,-0.020588854,-0.09785093,0.039992593,0.012910578,0.094094984,0.02117619,0.06758268,-0.09742841,0.06880695,-0.00032987754,0.0050983336,-0.03341494,0.019010287,-0.089999095,0.09407187,-0.029165616,-0.032074045,0.0035890248,0.099349216,0.0055552474,0.050976235,0.011247971,0.021357194,0.052730888,-0.038034238,0.05478972,0.105716586,0.016291477,0.108980164,0.10814203,-0.042486478,0.00659203,-0.006517861,-0.017847028,0.0037603125,0.040662315,-0.030742006,0.0031661002,0.017624384,0.05789647,-0.002206136,0.009744982,-0.03230846,-0.090841815,0.03681038,-0.088113196,0.11874008,0.045930807,0.0023115866,0.055023048,-0.02128332,0.079351865,-0.06768003,0.023713296,-0.019067196,3.1948504e-33,-0.05710833,-0.0101606725,-0.063466564,-0.08092137,-0.037043843,0.031093266,0.032598983,0.004457645,0.005740295,0.008327984,-0.02477964,0.051540695,-0.03410503,0.040080205,0.057572514,-0.16123688,-0.07812107,0.06013479,0.04670107,0.009449589,-0.052636445,-0.024773823,0.02690822,-0.034523983,0.010286329,-0.035306875,-0.04081293,0.013313726,-0.037652075,-0.01491592,0.017096614,0.04212605,-0.016412726,0.00018962799,-0.03545523,0.019579867,0.07682069,-0.02204794,-0.044240505,-0.07626127,-0.048655663,0.10024769,-0.010274072,-0.054897565,-0.12439236,-0.02318536,0.019457722,-0.007985635,-0.03722128,0.03137262,-0.08248051,0.027976139,0.02199911,-0.033353206,-0.051700685,-0.00015130675,-0.04395165,-0.096834384,0.023789,0.041331794,-0.011551556,0.07892461,-0.022264678,0.022576794,-0.049654953,0.11658619,0.025352556,0.06319953,-0.11649006,0.010219028,-0.043736532,-0.026094062,0.02805045,-0.030297868,0.080441386,0.032022677,-0.012331834,-0.013504899,-0.023467885,-0.06993975,-0.022800494,-0.007923741,0.061784346,-0.038510762,-0.024670742,-0.029049393,0.09686742,0.05291719,0.030025467,-0.008855068,-0.0019389951,-0.024374468,0.070086606,0.07975126,-0.010469389,-4.4732563e-33,-0.03517365,0.051808417,0.04097982,0.033409294,-0.01699612,-0.012118089,0.014258297,0.01631944,-0.07590088,-0.114455216,0.0010882062,0.012689413,-0.015041026,0.04589724,-0.089347616,-0.007180508,-0.0049858177,-0.028479101,0.01765283,-0.1054046,0.05246658,0.05807753,-0.009568819,0.035712034,-0.07002534,0.036326043,-0.0679036,0.0002256352,0.026232455,0.012982408,0.019598441,0.018622385,0.052233674,0.011914056,0.005941965,-0.016973345,-0.051878866,0.06183222,0.03061941,0.04041831,-0.0061867926,0.04013845,-0.055508114,0.0101720495,0.11219091,0.025958374,-0.06382838,0.021497544,0.103662774,0.0427279,-0.04897521,0.073114514,-0.0632307,-0.025937142,-0.107607014,0.014353267,0.046939727,-0.07472879,-0.0034768614,0.005560904,-0.040839575,0.03889369,-0.022462783,-0.14277779,0.070938826,0.023879157,0.02795238,-0.15900865,0.06755013,0.005809585,-0.025037628,0.018587438,-0.04296084,-0.009391255,0.029594148,0.04555913,0.02390756,0.014968313,-0.036860187,0.06719244,0.019326527,0.054734536,0.006246322,0.01996504,-0.074552484,0.021194328,-0.026073499,-0.061368875,-0.023903295,-0.0075700176,-0.021068973,-0.11225941,-0.03893311,0.01636903,0.019997818,-5.9521962e-08,-0.020360496,-0.070872724,0.015967373,0.08287608,0.027580766,-0.07107258,0.0005265348,0.05203665,0.0339103,0.009366281,0.074397184,0.042620182,-0.059755117,0.011636489,-0.027990304,0.033223897,-0.018769166,0.042640805,-0.00038335266,-0.049280718,-0.0004795793,0.03446119,0.031354006,0.008789563,0.052026328,-0.029795855,0.03688481,0.10595333,0.003417805,0.006899746,-0.025237866,0.05285308,-0.03693487,-0.06962168,-0.042989578,-0.059880797,-0.035618816,-0.010584988,0.06527933,0.0069591342,-0.027945496,-0.029474411,-0.026735496,0.049484126,0.0623141,-0.040814575,-0.13283272,-0.009251136,0.023256999,-0.107226476,0.063248254,0.07440245,0.012355829,0.05288682,0.06851536,-0.008741946,-0.088082775,0.010927832,-0.055538997,-0.010427307,-0.017134054,-0.08844598,-0.092645995,-0.025397362]')
('AAPL_2026Q3', 55, 'AAPL', 2026, 3, datetime.date(2026, 7, 30), 'roic.ai', "use the Mac is not covered by the same regulations as the iPhone and the iPad. Net-net, we're working with them and hope to reach some sort of solution. You look at China, last week we received approv", '[-0.0036255964,-0.07714022,0.122357205,-0.027799495,0.052493144,0.039741684,-0.008381875,0.015409264,-0.06582995,0.037277684,-0.0027872894,0.0092277145,-0.027438862,-0.0057593496,-0.039738696,0.035105694,0.009006005,-0.09463269,-0.044602618,0.013839807,0.033468626,0.008914205,0.034474213,-0.06476217,0.042439427,0.0439492,0.008011969,-0.004825587,-0.006574285,0.00030327853,-0.03076241,0.063970454,0.013334187,-0.034475237,0.0062542544,-0.02758592,0.006303654,-0.028905705,-0.019016454,-0.09964081,-0.009244808,-0.021743782,-0.005428898,0.038645864,0.06596401,-0.019789992,0.037338905,0.004095191,0.06532539,0.0056406516,0.019227663,0.03862937,0.014359737,-0.044058442,0.023305295,0.08821852,0.05001721,-0.056492444,0.041880142,0.05385938,-0.030660154,-0.06237411,0.0014635373,-0.01073005,0.04664859,0.0030332997,-0.079934485,-0.088350095,-0.039592754,0.041394465,0.074830264,-0.07357449,-0.0035517877,-0.020980276,-0.015981248,-0.014328319,0.070749775,-0.010187824,0.06569031,-0.061014194,0.023723237,0.0142498,0.06768853,0.012596642,0.057181563,-0.12572415,-0.013615983,0.0019736143,-0.024590915,-0.019163858,0.046427388,0.03818738,0.104490675,0.046038367,0.11619534,0.084010296,-0.016827099,-0.018753257,-0.0051730466,0.046785742,0.059871927,0.024032345,-0.103067085,-0.06495324,-0.044493005,-0.0046894774,0.010189582,0.01517342,0.07554064,0.071202,0.025326775,0.016281104,-0.029637491,0.0077958317,-0.04213001,-0.0069738547,0.022420226,0.058920793,0.12038147,0.030127695,-0.06612247,0.0969179,-0.020032577,0.051799614,0.030204257,0.028886039,-0.020692209,1.3864307e-33,-0.10910394,0.0347992,-0.055892218,-0.101356916,-0.047000315,-0.04663569,0.08629779,0.06701758,-0.0014850317,0.0024912558,-0.07358342,0.03906365,-0.11455672,0.010107071,0.056608867,-0.11164641,-0.00085703144,0.01857447,0.055087835,-0.008825922,0.050979596,-0.07759757,0.022691786,-0.07450695,0.02271511,-0.030065686,0.018961139,-0.020913268,0.06420937,-0.0058373287,-0.015722087,0.028156707,0.002551391,-0.0638332,-0.08557872,0.03150298,-0.01703429,0.017595764,-0.030704314,0.07969732,-0.13636068,0.065966144,-0.028578505,-0.07511239,-0.06851501,-0.022433206,-0.0015414315,-0.03568505,-0.052427944,0.039006572,-0.10082165,0.011007439,0.021665055,-0.064733535,-0.04503268,-0.051045626,0.021955455,-0.05638238,0.03464765,0.038635164,0.03065002,-0.02997803,-0.07515692,0.06528481,-0.07587527,0.08996406,0.027529199,0.0009644022,-0.05897198,0.035140105,-0.03593333,0.00827928,0.0073834835,-0.07036831,0.07501568,-0.0017616411,-0.079769894,0.030522138,-0.07277349,-0.054927062,-0.020498548,0.051977158,0.013581359,0.041506488,0.032875832,0.034229785,0.050679687,0.040770594,0.09181318,0.0325151,-0.014406087,-0.0014079923,-0.0299656,0.05206022,-0.021849293,-2.3805641e-33,-0.037328523,0.052207224,-0.013546278,-0.0069763656,-0.059544545,-0.036380637,-0.03885513,0.036000885,-0.033265524,-0.07490937,-0.0056694434,0.008027586,0.028273787,-0.015106781,-0.083897,-0.04014321,-0.07571031,-0.01678042,0.025914537,-0.044373315,0.08665098,0.04953429,-0.03694622,0.0037911213,-0.03813818,0.012585854,-0.055867184,0.042483263,0.040050127,0.01659432,-0.01343965,-0.04110515,0.0016872402,-0.043022633,0.053194582,0.032632798,-0.033765625,0.023518823,-0.00800944,0.051544495,0.0766907,-0.037434213,-0.067383125,-0.012945803,0.06373682,-0.018783825,-0.03625322,0.052437566,0.025871957,-0.016165094,-0.046309985,0.035921454,-0.061004203,-0.013819319,-0.11398501,0.025056506,0.09727005,-0.006790316,-0.018635137,-0.011082641,-0.0028948293,0.051052693,0.016243983,-0.06558687,0.055691816,0.034059547,0.051493835,-0.061657548,0.11497462,-0.020339878,-0.049930673,-0.025441458,-0.008603642,0.009836543,0.056848764,0.05787984,0.04065419,0.038279247,-0.034400485,0.028929532,0.071583465,0.09755624,0.05018845,0.028535753,0.03590795,0.010178639,0.07544982,-0.08129209,-0.017193394,0.08302158,-0.08567398,-0.051588707,-0.046483625,0.027527463,-0.07511155,-5.8486815e-08,-0.021985432,0.00769202,0.0035915824,0.06337659,-0.044013847,0.0026234216,-0.051434394,-0.003412353,0.06609777,-0.032847594,0.04082681,-0.003170072,-0.085408114,0.05779309,-0.06742179,0.05904414,0.0070520886,0.06467341,0.020180546,-0.02589371,-0.016517546,0.07151339,-0.017427474,-0.009573763,-0.022516768,0.042219102,0.013044893,0.08726012,-0.036780242,0.04143269,-0.08881881,0.04173835,0.01062352,-0.0016766604,-0.07247105,-0.060517747,-0.037706744,-0.026896004,0.06076325,-0.014901114,-0.04325717,-0.009321138,-0.04403476,-0.040001094,0.090492666,-0.10870225,-0.13186282,-0.03227862,0.1405508,0.002348131,0.044584125,-0.043662846,0.045663286,0.056801345,0.088737324,-0.014270922,-0.00831905,-0.070690304,-0.076577656,0.03998027,0.0522949,-0.13112949,-0.04570658,-0.0011857745]')

In [25]:
conn = psycopg.connect(os.environ["PG_CONN_STR"])
row = conn.execute("""
    SELECT vector_dims(embedding)
    FROM earnings_chunks
    LIMIT 5
""").fetchall()

print(row)
conn.close()

[(384,), (384,), (384,), (384,), (384,)]

In [ ]:
from src.data_ingestion import ingest_ticker
ingest_ticker("AAPL")

In [ ]:
from src.data_ingestion import ingest_ticker
for ticker in ["AAPL", "MSFT", "META", "GOOG", "TSLA"]:
    ingest_ticker(ticker)

/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 602, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3048, in run_cell
    result = self._run_cell(
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3103, in _run_cell
    result = runner(coro)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3308, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3490, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/cv/bbbq9ykj0jg6pt6c7tx5_vjh0000gn/T/ipykernel_45815/1441274102.py", line 1, in <module>
    from src.ingestion.data_ingestion import ingest_ticker
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/src/ingestion/data_ingestion.py", line 7, in <module>
    from sentence_transformers import SentenceTransformer
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/sentence_transformers/__init__.py", line 10, in <module>
    from sentence_transformers.backend import (
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/sentence_transformers/backend/__init__.py", line 3, in <module>
    from .load import load_onnx_model, load_openvino_model
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/sentence_transformers/backend/load.py", line 7, in <module>
    from transformers.configuration_utils import PretrainedConfig
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/transformers/__init__.py", line 27, in <module>
    from . import dependency_versions_check
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/transformers/utils/__init__.py", line 24, in <module>
    from .auto_docstring import (
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/transformers/utils/auto_docstring.py", line 30, in <module>
    from .generic import ModelOutput
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/transformers/utils/generic.py", line 51, in <module>
    import torch
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/google/auth/__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/google/oauth2/__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)

In [3]:
# quick check to see if the data was inserted correctly
import os
import psycopg

conn = psycopg.connect(os.environ["PG_CONN_STR"])
count = conn.execute("SELECT COUNT(*) FROM earnings_chunks").fetchone()[0]
print("total rows:", count)
conn.close()

total rows: 439

In [4]:
conn = psycopg.connect(os.environ["PG_CONN_STR"])
rows = conn.execute("""
    SELECT symbol, COUNT(*) AS n_rows
    FROM earnings_chunks
    GROUP BY symbol
    ORDER BY n_rows DESC, symbol
""").fetchall()

for row in rows:
    print(row)

conn.close()

('AAPL', 177)
('META', 71)
('MSFT', 68)
('GOOG', 63)
('TSLA', 60)

In [5]:
# View the table in pandas
import pandas as pd
import os
import psycopg

conn = psycopg.connect(os.environ["PG_CONN_STR"])

df = pd.read_sql("""
    SELECT *
    FROM earnings_chunks
    ORDER BY symbol, year, quarter, chunk_index
""", conn)

conn.close()

df

/var/folders/cv/bbbq9ykj0jg6pt6c7tx5_vjh0000gn/T/ipykernel_29089/243384069.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("""

,id,doc_id,chunk_index,text,embedding,symbol,year,quarter,date,source,text_search
0,119,AAPL_2026Q3,0,"Suhasini Chandramouli: Good afternoon, welcome...","[-0.064011656,0.024912179,0.022694364,0.013237...",AAPL,2026,3,2026-07-30,roic.ai,'2026':12 'actual':118 'afternoon':4 'also':44...
1,120,AAPL_2026Q3,1,e potential impact to the company's business a...,"[-0.0678837,0.06957855,0.06610086,-0.009652353...",AAPL,2026,3,2026-07-30,roic.ai,"'10':44,48,76 '109.4':154 '16':159 '2026':84 '..."
2,121,AAPL_2026Q3,2,"eased to report $109.4 billion in revenue, up ...","[-0.0016072415,-0.053820774,0.004542911,-0.011...",AAPL,2026,3,2026-07-30,roic.ai,'109.4':4 '16':9 '22':50 '29':78 '30.7':94 'ab...
3,122,AAPL_2026Q3,3,developed and emerging markets and saw double-...,"[-0.107194476,-0.09426214,0.0046844664,-0.0452...",AAPL,2026,3,2026-07-30,roic.ai,"'absolut':60 'across':54 'ai':38,72,111 'all-n..."
4,123,AAPL_2026Q3,4,"excited about it, we are feeling incredibly e...","[-0.08523346,-0.008796054,0.020351894,-0.02406...",AAPL,2026,3,2026-07-30,roic.ai,'22':151 '54.3':148 'academi':75 'achiev':157 ...
...,...,...,...,...,...,...,...,...,...,...,...
455,435,TSLA_2026Q2,55,"neja : Yes. Basically, the amount of solar man...","[-0.08364076,0.017624052,0.02091572,0.04679709...",TSLA,2026,2,2026-07-22,roic.ai,'almost':76 'amount':5 'axelrod':158 'back':91...
456,436,TSLA_2026Q2,56,follow-up that we can wrap up with?\n\nDan Le...,"[-0.040536866,-0.00094406685,0.052946944,0.044...",TSLA,2026,2,2026-07-22,roic.ai,"'address':33,83 'advantag':103 'also':144 'awe..."
457,437,TSLA_2026Q2,57,"briefly, but for balancing power from wind ge...","[-0.07177704,0.039566245,0.044460297,0.0607338...",TSLA,2026,2,2026-07-22,roic.ai,"'100':168 '70':166 'act':176 'ai':97,102,105,1..."
458,438,TSLA_2026Q2,58,"t period of time, you can have -- during a tra...","[0.0021983818,0.039089333,0.057418592,0.066452...",TSLA,2026,2,2026-07-22,roic.ai,'0.5':179 '1.2':162 '1.3':164 '100':20 '2.5':1...
459,439,TSLA_2026Q2,59,"se there's, I think, around 1.2 or 1.3 terawat...","[-0.042104464,0.0124058155,0.059191205,0.05053...",TSLA,2026,2,2026-07-22,roic.ai,'0.5':24 '1.2':7 '1.3':9 '2.5':30 'appreci':87...

In [ ]:
conn = psycopg.connect(os.environ["PG_CONN_STR"])
df = pd.read_sql("""
    SELECT id, doc_id, chunk_index, symbol, year, quarter, date, source, text
    FROM earnings_chunks
    ORDER BY symbol, year, quarter, chunk_index
""", conn)
conn.close()

df

In [ ]:
# remove duplicates from the earnings_chunks table based on doc_id and chunk_index, keeping the one with the highest id
import os
import psycopg

conn = psycopg.connect(os.environ["PG_CONN_STR"])

conn.execute("""
    DELETE FROM earnings_chunks a
    USING earnings_chunks b
    WHERE a.id < b.id
      AND a.doc_id = b.doc_id
      AND a.chunk_index = b.chunk_index
""")

conn.commit()
conn.close()

### Below step is a good pattern if you expect to ingest more transcripts or want the pipeline to be more efficient and orchestration-friendly. For one transcript at a time, your current ingest_ticker() path is simpler and perfectly fine.

In [ ]:
3. Orchestration with batching (borrowed from your FAQ example)
To combine chunking + embedding while still batching:

python
from tqdm.auto import tqdm
from src.data_ingestion import load_local_transcripts, normalize_example, chunk_text
from src.embeddings import embed_chunks

transcripts = load_local_transcripts()
normalized = [normalize_example(t) for t in transcripts]

all_chunks = []
chunk_meta = []  # to keep doc_id / chunk_index alongside

for nt in normalized:
    chunks = chunk_text(nt["text"], chunk_size=1000, overlap=150)
    for idx, ch in enumerate(chunks):
        all_chunks.append(ch)
        chunk_meta.append({
            "doc_id": nt["doc_id"],
            "symbol": nt["metadata"]["symbol"],
            "year": nt["metadata"]["year"],
            "quarter": nt["metadata"]["quarter"],
            "date": nt["metadata"]["date"],
            "source": nt["metadata"]["source"],
            "chunk_index": idx,
        })

# Batch embeddings over all chunks
batch_size = 64
all_vectors = []

for i in tqdm(range(0, len(all_chunks), batch_size)):
    batch = all_chunks[i:i + batch_size]
    batch_vectors = embed_chunks(batch)  # uses model.encode internally
    all_vectors.extend(batch_vectors)

# Now you have flat lists: chunk_meta[i], all_chunks[i], all_vectors[i]
# Insert into PGVector
def vec_to_str(vector):
    return "[" + ",".join(str(x) for x in vector) + "]"

import psycopg, os
from dotenv import load_dotenv

load_dotenv()
conn = psycopg.connect(os.environ["PG_CONN_STR"])

for meta, text, vec in tqdm(zip(chunk_meta, all_chunks, all_vectors), total=len(all_chunks)):
    conn.execute(
        """
        INSERT INTO earnings_chunks (
            doc_id, chunk_index, text, embedding,
            symbol, year, quarter, date, source
        )
        VALUES (%s, %s, %s, %s::vector, %s, %s, %s, %s, %s)
        """,
        (
            meta["doc_id"],
            meta["chunk_index"],
            text,
            vec_to_str(vec),
            meta["symbol"],
            meta["year"],
            meta["quarter"],
            meta["date"],
            meta["source"],
        ),
    )

conn.commit()

# test scheduled ingestion

In [4]:
# Connect and confirm INTC chunks

import os
import psycopg
import pandas as pd

pg_conn_str = os.environ["PG_CONN_STR"]

query = """
SELECT
    doc_id,
    symbol,
    year,
    quarter,
    date,
    COUNT(*) AS chunk_count
FROM earnings_chunks
WHERE symbol = %s
GROUP BY doc_id, symbol, year, quarter, date
ORDER BY date DESC;
"""

with psycopg.connect(pg_conn_str) as conn:
    with conn.cursor() as cur:
        cur.execute(query, ("LRCX",))
        rows = cur.fetchall()
        columns = [column.name for column in cur.description]

intc_chunks = pd.DataFrame(rows, columns=columns)
intc_chunks

        doc_id symbol  year  quarter        date  chunk_count
0  LRCX_2026Q4   LRCX  2026        4  2026-07-29           82

In [6]:
#  Inspect stored chunk text
sample_query = """
SELECT
    doc_id,
    chunk_index,
    text
FROM earnings_chunks
WHERE symbol = %s
ORDER BY chunk_index
LIMIT 3;
"""

with psycopg.connect(pg_conn_str) as conn:
    with conn.cursor() as cur:
        cur.execute(sample_query, ("LRCX",))
        sample_rows = cur.fetchall()
        sample_columns = [column.name for column in cur.description]

intc_sample_chunks = pd.DataFrame(sample_rows, columns=sample_columns)

for _, row in intc_sample_chunks.iterrows():
    print(f"\n--- {row['doc_id']} | chunk {row['chunk_index']} ---")
    print(row["text"][:800])

--- LRCX_2026Q4 | chunk 0 ---
Operator: Thank you to everyone for joining Robinhood's Q2 2026 Earnings Call, whether you're tuning into the live stream or here with us in person. With us today are Chairman and CEO, Vlad Tenev; CFO, Shiv Verma; and VP of Corporate Finance and Investor Relations, Chris Koegel. Vlad and Shiv will offer opening remarks and then open the call to Q&A.  During the Q&A portion of the call, we will answer questions from the audience, which includes institutional research analysts, finance content creators who may hold an ownership position in Robinhood, and both institutional and retail shareholders.  As a reminder, today's call will contain forward-looking statements. Actual results could differ materially from our current expectations, and we may not provide updates unless legally required. P

--- LRCX_2026Q4 | chunk 1 ---
, including regulatory developments that we continue to monitor, are described in the press release we issued today, the earnings presentation and our SEC filings, all of which can be found at investors.robinhood.com. Today's discussion will also include non-GAAP financial measures. Reconciliations to the GAAP measures we consider most directly comparable can be found in the earnings presentation.  With that, please welcome Vlad and Shiv.

Vladimir Tenev: Thank you guys for joining. Thanks for the warm welcome, and it's awesome to see a packed house in here. We are back again at NASDAQ in New York City, taking a big bite out of the big apple with Shiv here and Chris. Largest audience yet for an earnings event. I remember, Shiv, last year, it was when we did the first event with analysts in

--- LRCX_2026Q4 | chunk 2 ---
 not too many people did, but the people that did had a lot of fun, and now I'm glad to see the word has spread.  So it's really great to see shareholders, analysts, buy-side and sell-side, content creators in the audience here. It's been about 5 years, actually, I think, exactly 5 years since we rang the bell at the NASDAQ. And in that time, we've really accomplished significant growth, and we've delivered for our customers in that time period since IPO, total platform assets have quadrupled and adjusted EBITDA has more than 8x.  But one thing hasn't changed, why we exist? Robinhood exists to make everyone an owner. And I think that's a unique vision. I don't think a lot of companies are going after us. It's a powerful vision, not just for each individual customer, but I think also for so

In [7]:
# Save baseline count for idempotency
count_query = """
SELECT COUNT(*) AS total_chunks
FROM earnings_chunks
WHERE symbol = %s;
"""

with psycopg.connect(pg_conn_str) as conn:
    before_rerun_count = conn.execute(
        count_query,
        ("LRCX",)
    ).fetchone()[0]

before_rerun_count

82

# database

In [7]:
conn = psycopg.connect(os.environ["PG_CONN_STR"])

row = conn.execute("""
    SELECT column_name, is_generated, generation_expression
    FROM information_schema.columns
    WHERE table_name = 'earnings_chunks'
      AND column_name = 'text_search'
""").fetchone()

print(row)
conn.close()

('text_search', 'ALWAYS', '(setweight(to_tsvector(\'simple\'::regconfig, ((((COALESCE(symbol, \'\'::text) || \' \'::text) || COALESCE((year)::text, \'\'::text)) || \' \'::text) || COALESCE((quarter)::text, \'\'::text))), \'A\'::"char") || setweight(to_tsvector(\'english\'::regconfig, COALESCE(text, \'\'::text)), \'B\'::"char"))')

In [8]:
conn = psycopg.connect(os.environ["PG_CONN_STR"])

missing = conn.execute("""
    SELECT COUNT(*)
    FROM earnings_chunks
    WHERE text_search IS NULL
""").fetchone()[0]

print("Rows with missing text_search:", missing)
conn.close()

Rows with missing text_search: 0

## changed the chunk size, reingest

In [2]:
# Count current rows
import os
import psycopg

with psycopg.connect(os.environ["PG_CONN_STR"]) as conn:
    row_count = conn.execute("""
        SELECT COUNT(*)
        FROM earnings_chunks
    """).fetchone()[0]

print("Rows before reset:", row_count)

Rows before reset: 705

In [3]:
# delete rows
with psycopg.connect(os.environ["PG_CONN_STR"]) as conn:
    conn.execute("""
        TRUNCATE TABLE earnings_chunks RESTART IDENTITY
    """)

print("All earnings_chunks rows deleted.")

All earnings_chunks rows deleted.

In [4]:
with psycopg.connect(os.environ["PG_CONN_STR"]) as conn:
    row_count = conn.execute("""
        SELECT COUNT(*)
        FROM earnings_chunks
    """).fetchone()[0]

print("Rows after reset:", row_count)

Rows after reset: 0

In [5]:
from src.data_ingestion import ingest_ticker

tickers = ["AAPL", "MSFT", "META", "GOOG", "TSLA"]

for ticker in tickers:
    print(f"Ingesting {ticker}...")
    ingest_ticker(ticker)

Ingesting AAPL...
[INFO] AAPL: inserted 50 chunks for AAPL_2026Q3.
Ingesting MSFT...
[INFO] MSFT: inserted 58 chunks for MSFT_2026Q4.
Ingesting META...
[INFO] META: inserted 61 chunks for META_2026Q2.
Ingesting GOOG...
[INFO] GOOG: inserted 54 chunks for GOOG_2026Q2.
Ingesting TSLA...
[INFO] TSLA: inserted 51 chunks for TSLA_2026Q2.

In [3]:
from src.data_ingestion import ingest_ticker

tickers = ["NVDA", "TSM", "AVGO", "AMD", "LRCX"]

for ticker in tickers:
    print(f"Ingesting {ticker}...")
    ingest_ticker(ticker)

Ingesting NVDA...
[INFO] NVDA: inserted 47 chunks for NVDA_2027Q1.
Ingesting TSM...
[INFO] TSM: inserted 50 chunks for TSM_2026Q2.
Ingesting AVGO...
[INFO] AVGO: inserted 39 chunks for AVGO_2026Q2.
Ingesting AMD...
[INFO] AMD: inserted 51 chunks for AMD_2026Q2.
Ingesting LRCX...
[INFO] LRCX: inserted 69 chunks for LRCX_2026Q4.

In [6]:
import os
import psycopg

with psycopg.connect(os.environ["PG_CONN_STR"]) as conn:
    rows = conn.execute("""
        SELECT
            symbol,
            doc_id,
            COUNT(*) AS chunk_count,
            MIN(chunk_index) AS first_chunk,
            MAX(chunk_index) AS last_chunk
        FROM earnings_chunks
        GROUP BY symbol, doc_id
        ORDER BY symbol, doc_id
    """).fetchall()

for row in rows:
    print(row)

('AAPL', 'AAPL_2026Q3', 50, 0, 49)
('GOOG', 'GOOG_2026Q2', 54, 0, 53)
('META', 'META_2026Q2', 61, 0, 60)
('MSFT', 'MSFT_2026Q4', 58, 0, 57)
('TSLA', 'TSLA_2026Q2', 51, 0, 50)

In [7]:
with psycopg.connect(os.environ["PG_CONN_STR"]) as conn:
    row_count = conn.execute("""
        SELECT COUNT(*)
        FROM earnings_chunks
    """).fetchone()[0]

print("Rows after reingest:", row_count)

Rows after reingest: 274