In [ ]:
from pathlib import Path
import os
import json
from dotenv import load_dotenv
from src.data_ingestion import fetch_data, normalize_example, chunk_text, load_to_db, embed_chunks, ingest_ticker
import psycopg

/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/google/auth/__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/google/oauth2/__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)

In [2]:
# View the table in pandas
import pandas as pd
import os
import psycopg

conn = psycopg.connect(os.environ["PG_CONN_STR"])
df = pd.read_sql("""
    SELECT id, doc_id, chunk_index, symbol, year, quarter, date, source, text
    FROM earnings_chunks
    ORDER BY symbol, year, quarter, chunk_index
""", conn)
conn.close()

df.head(20)

/var/folders/cv/bbbq9ykj0jg6pt6c7tx5_vjh0000gn/T/ipykernel_62043/901644907.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("""

,id,doc_id,chunk_index,symbol,year,quarter,date,source,text
0,119,AAPL_2026Q3,0,AAPL,2026,3,2026-07-30,roic.ai,"Suhasini Chandramouli: Good afternoon, welcome..."
1,120,AAPL_2026Q3,1,AAPL,2026,3,2026-07-30,roic.ai,e potential impact to the company's business a...
2,121,AAPL_2026Q3,2,AAPL,2026,3,2026-07-30,roic.ai,"eased to report $109.4 billion in revenue, up ..."
3,122,AAPL_2026Q3,3,AAPL,2026,3,2026-07-30,roic.ai,developed and emerging markets and saw double-...
4,123,AAPL_2026Q3,4,AAPL,2026,3,2026-07-30,roic.ai,"excited about it, we are feeling incredibly e..."
5,124,AAPL_2026Q3,5,AAPL,2026,3,2026-07-30,roic.ai,iPhone revenue for the June quarter was $54.3...
6,125,AAPL_2026Q3,6,AAPL,2026,3,2026-07-30,roic.ai,ac delivered its best June quarter yet with $1...
7,126,AAPL_2026Q3,7,AAPL,2026,3,2026-07-30,roic.ai,d creation across a broad range of AI workload...
8,127,AAPL_2026Q3,8,AAPL,2026,3,2026-07-30,roic.ai,"the ultimate go-anywhere, do anything device ..."
9,128,AAPL_2026Q3,9,AAPL,2026,3,2026-07-30,roic.ai,had. We're delivering useful features backed b...
10,129,AAPL_2026Q3,10,AAPL,2026,3,2026-07-30,roic.ai,"es are intuitive and useful, while also deeply..."
11,130,AAPL_2026Q3,11,AAPL,2026,3,2026-07-30,roic.ai,That's why developers and researchers are incr...
12,131,AAPL_2026Q3,12,AAPL,2026,3,2026-07-30,roic.ai,"is year's Emmy Awards, where Apple has landed ..."
13,132,AAPL_2026Q3,13,AAPL,2026,3,2026-07-30,roic.ai,"teams. In retail, we were pleased to announce ..."
14,133,AAPL_2026Q3,14,AAPL,2026,3,2026-07-30,roic.ai,re also using on-device speech recognition to ...
15,134,AAPL_2026Q3,15,AAPL,2026,3,2026-07-30,roic.ai,n components and cutting-edge wireless connect...
16,135,AAPL_2026Q3,16,AAPL,2026,3,2026-07-30,roic.ai,ntire advanced manufacturing ecosystem. We hav...
17,136,AAPL_2026Q3,17,AAPL,2026,3,2026-07-30,roic.ai,"r-over-year, a June quarter revenue record. We..."
18,137,AAPL_2026Q3,18,AAPL,2026,3,2026-07-30,roic.ai,"ve this favorable impact, we would have been a..."
19,138,AAPL_2026Q3,19,AAPL,2026,3,2026-07-30,roic.ai,tails for each of our revenue categories. iPho...

In [5]:
load_dotenv()
conn_str = os.getenv("PG_CONN_STR")

In [6]:
sql = """
ALTER TABLE earnings_chunks
ADD COLUMN IF NOT EXISTS text_search tsvector;
"""
with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        cur.execute(sql)

In [7]:
sql = """
UPDATE earnings_chunks
SET text_search = to_tsvector('english', text);
"""
with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        cur.execute(sql)

In [8]:
sql = """
CREATE INDEX IF NOT EXISTS earnings_chunks_text_search_idx
ON earnings_chunks
USING GIN (text_search);
"""
with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        cur.execute(sql)

In [14]:
# inspect the new column and index
import os
import pandas as pd
import psycopg
from dotenv import load_dotenv

load_dotenv()

with psycopg.connect(os.environ["PG_CONN_STR"]) as conn:
    with conn.cursor() as cur:
        cur.execute("""
            SELECT id, doc_id, chunk_index, symbol, year, quarter, date, source, text, text_search
            FROM earnings_chunks
            ORDER BY symbol, year, quarter, chunk_index
        """)
        rows = cur.fetchall()
        cols = [desc[0] for desc in cur.description]

df = pd.DataFrame(rows, columns=cols)
df.head(20)

,id,doc_id,chunk_index,symbol,year,quarter,date,source,text,text_search
0,119,AAPL_2026Q3,0,AAPL,2026,3,2026-07-30,roic.ai,"Suhasini Chandramouli: Good afternoon, welcome...",'2026':12 'actual':118 'afternoon':4 'also':44...
1,120,AAPL_2026Q3,1,AAPL,2026,3,2026-07-30,roic.ai,e potential impact to the company's business a...,"'10':44,48,76 '109.4':154 '16':159 '2026':84 '..."
2,121,AAPL_2026Q3,2,AAPL,2026,3,2026-07-30,roic.ai,"eased to report $109.4 billion in revenue, up ...",'109.4':4 '16':9 '22':50 '29':78 '30.7':94 'ab...
3,122,AAPL_2026Q3,3,AAPL,2026,3,2026-07-30,roic.ai,developed and emerging markets and saw double-...,"'absolut':60 'across':54 'ai':38,72,111 'all-n..."
4,123,AAPL_2026Q3,4,AAPL,2026,3,2026-07-30,roic.ai,"excited about it, we are feeling incredibly e...",'22':151 '54.3':148 'academi':75 'achiev':157 ...
5,124,AAPL_2026Q3,5,AAPL,2026,3,2026-07-30,roic.ai,iPhone revenue for the June quarter was $54.3...,"'10.4':154 '17':112,131 '17e':138 '22':11 '29'..."
6,125,AAPL_2026Q3,6,AAPL,2026,3,2026-07-30,roic.ai,ac delivered its best June quarter yet with $1...,'10.4':9 '29':16 'ac':1 'accord':48 'achiev':9...
7,126,AAPL_2026Q3,7,AAPL,2026,3,2026-07-30,roic.ai,d creation across a broad range of AI workload...,"'6.2':131 'across':3,44 'agent':29 'ai':8,30,1..."
8,127,AAPL_2026Q3,8,AAPL,2026,3,2026-07-30,roic.ai,"the ultimate go-anywhere, do anything device ...",'6':96 '7.9':93 'accessori':91 'achiev':108 'a...
9,128,AAPL_2026Q3,9,AAPL,2026,3,2026-07-30,roic.ai,had. We're delivering useful features backed b...,"'2':84 '3':70 'across':56,132 'activ':78 'ai':..."
10,129,AAPL_2026Q3,10,AAPL,2026,3,2026-07-30,roic.ai,"es are intuitive and useful, while also deeply...","'2017':55 'advanc':157 'ai':47,75,129,136 'als..."
11,130,AAPL_2026Q3,11,AAPL,2026,3,2026-07-30,roic.ai,That's why developers and researchers are incr...,'12':34 '30.7':25 '89':155 'ad':116 'advanc':1...
12,131,AAPL_2026Q3,12,AAPL,2026,3,2026-07-30,roic.ai,"is year's Emmy Awards, where Apple has landed ...",'170':92 '19':53 '3':75 '800':76 '850':71 '89'...
13,132,AAPL_2026Q3,13,AAPL,2026,3,2026-07-30,roic.ai,"teams. In retail, we were pleased to announce ...","'access':105,136 'across':74 'ad':166 'also':1..."
14,133,AAPL_2026Q3,14,AAPL,2026,3,2026-07-30,roic.ai,re also using on-device speech recognition to ...,"'600':91 'ad':21 'advanc':129 'agreement':141,..."
15,134,AAPL_2026Q3,15,AAPL,2026,3,2026-07-30,roic.ai,n components and cutting-edge wireless connect...,"'30':31 'advanc':77,93,147 'agreement':15 'ahe..."
16,135,AAPL_2026Q3,16,AAPL,2026,3,2026-07-30,roic.ai,ntire advanced manufacturing ecosystem. We hav...,'109.4':147 '16':151 'advanc':2 'afternoon':13...
17,136,AAPL_2026Q3,17,AAPL,2026,3,2026-07-30,roic.ai,"r-over-year, a June quarter revenue record. We...",'12':91 '140':169 '18':35 '30.7':88 '40.1':167...
18,137,AAPL_2026Q3,18,AAPL,2026,3,2026-07-30,roic.ai,"ve this favorable impact, we would have been a...",'0.11':108 '110':61 '140':26 '17':169 '19.1':7...
19,138,AAPL_2026Q3,19,AAPL,2026,3,2026-07-30,roic.ai,tails for each of our revenue categories. iPho...,"'10.4':121 '17':23,103 '22':14 '29':124 '451':..."

In [ ]:
# test index.py
from src.index import text_search, vector_search, hybrid_search

query = "what did apple say about revenue?"

text_results = text_search(query, limit=5)
vector_results = vector_search(query, limit=5)
hybrid_results = hybrid_search(query, limit=5)

/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
for name, results in [
    ("TEXT", text_results),
    ("VECTOR", vector_results),
    ("HYBRID", hybrid_results),
]:
    print(f"\n=== {name} ===")
    for r in results:
        print(r["symbol"], r["year"], r["quarter"], r.get("score"), r["text"][:200])

=== TEXT ===
AAPL 2026 3 0.084645405 That's why developers and researchers are increasingly using Apple devices to build ever more advanced tools and models. Turning to services, revenue was $30.7 billion, a June quarter revenue record a
AAPL 2026 3 0.08248389 ssories revenue was $7.9 billion, up 6% year-over-year, driven by strength in wearables and accessories, and we saw growth in both developed and emerging markets. The wearables install base reached a
AAPL 2026 3 0.075990885 under a court ruling impacting the link-out transactions. We're pleased the Supreme Court will hear our appeal. Despite this, the App Store did set a June quarter revenue record. We take a step back.
AAPL 2026 3 0.07366894 ac delivered its best June quarter yet with $10.4 billion in revenue, growing an impressive 29% from a year ago despite significant supply constraints. This revenue growth was driven by the incredible
AAPL 2026 3 0.07366894 es are intuitive and useful, while also deeply integrated in a way that's personal and private with the latest models running on-device and on servers using private cloud compute. We began laying the

=== VECTOR ===
AAPL 2026 3 0.6701093912124634 tails for each of our revenue categories. iPhone revenue was $54.3 billion, up 22% year-over-year, driven by the iPhone 17 family. We grew double digits in the vast majority of markets we track and re
AAPL 2026 3 0.6033275723457336 ssories revenue was $7.9 billion, up 6% year-over-year, driven by strength in wearables and accessories, and we saw growth in both developed and emerging markets. The wearables install base reached a
AAPL 2026 3 0.6011936068534851 eased to report $109.4 billion in revenue, up 16% from a year ago and a June quarter record. We were able to achieve this despite supply constraints and sequential foreign exchange headwinds. We conti
AAPL 2026 3 0.5298841279814176 That's why developers and researchers are increasingly using Apple devices to build ever more advanced tools and models. Turning to services, revenue was $30.7 billion, a June quarter revenue record a
MSFT 2026 4 0.5141790815698563 ing margins with a strong focus on efficiencies and investment returns, were relatively unchanged year-over-year at 41%. Now to More Personal Computing. Revenue was $12.9 billion and declined 4% and 5

=== HYBRID ===
AAPL 2026 3 0.08248389 ssories revenue was $7.9 billion, up 6% year-over-year, driven by strength in wearables and accessories, and we saw growth in both developed and emerging markets. The wearables install base reached a
AAPL 2026 3 0.084645405 That's why developers and researchers are increasingly using Apple devices to build ever more advanced tools and models. Turning to services, revenue was $30.7 billion, a June quarter revenue record a
AAPL 2026 3 0.6701093912124634 tails for each of our revenue categories. iPhone revenue was $54.3 billion, up 22% year-over-year, driven by the iPhone 17 family. We grew double digits in the vast majority of markets we track and re
AAPL 2026 3 0.075990885 under a court ruling impacting the link-out transactions. We're pleased the Supreme Court will hear our appeal. Despite this, the App Store did set a June quarter revenue record. We take a step back.
AAPL 2026 3 0.6011936068534851 eased to report $109.4 billion in revenue, up 16% from a year ago and a June quarter record. We were able to achieve this despite supply constraints and sequential foreign exchange headwinds. We conti

In [ ]:
from src.index import _connect

query = "what did apple say about revenue?"

with _connect() as conn:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT websearch_to_tsquery('english', %s)::text",
            (query,)
        )
        result = cur.fetchone()[0]

result

"'appl' & 'say' & 'revenu'"

In [15]:
with _connect() as conn:
    with conn.cursor() as cur:
        cur.execute("""
            SELECT count(*)
            FROM earnings_chunks
            WHERE text_search @@ to_tsquery('english', 'revenu')
        """)
        count = cur.fetchone()[0]

count

83

In [20]:
with _connect() as conn:
    with conn.cursor() as cur:
        cur.execute("""
            SELECT count(*)
            FROM earnings_chunks
            WHERE text_search @@ websearch_to_tsquery('english', 'apple revenue')
        """)
        count = cur.fetchone()[0]

count

10

In [3]:
import os
from dotenv import load_dotenv

load_dotenv()
os.getenv("PG_CONN_STR")

'postgresql://raguser:ragpass@localhost:5432/ragdb'

In [ ]:
from src.rag_helper_project import ask

result = ask("What did Apple say about margins?")
print(result["answer"])

/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/google/auth/__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/google/oauth2/__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
/Users/camillecu/Downloads/KUL/llm_project/llm_project2026/llmproject/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Apple's CFO, Kevan Parekh, acknowledged a question regarding gross margins. An analyst noted that Apple delivered a 48% gross margin in the quarter (without the tariff refund benefit) and guided to approximately 46.5%. The analyst asked about the sequential drivers, including the impact of FX and commodity costs, but the provided context does not include Kevan Parekh's detailed response to this question.