In [1]:
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / "src"))

os.chdir(PROJECT_ROOT)

print("Working directory:", Path.cwd())
print("Source directory:", PROJECT_ROOT / "src")

Working directory: /Users/camillecu/Downloads/KUL/llm_project/llm_project2026
Source directory: /Users/camillecu/Downloads/KUL/llm_project/llm_project2026/src

In [2]:
import json
from dotenv import load_dotenv
from src.data_ingestion import fetch_data, normalize_example, chunk_text, load_to_db, embed_chunks, ingest_ticker
import psycopg

In [5]:
# View the table in pandas
import pandas as pd
import os
import psycopg

conn = psycopg.connect(os.environ["PG_CONN_STR"])
df = pd.read_sql("""
    SELECT *
    FROM earnings_chunks
    ORDER BY symbol, year, quarter, chunk_index
""", conn)
conn.close()

df

/var/folders/cv/bbbq9ykj0jg6pt6c7tx5_vjh0000gn/T/ipykernel_6422/946472184.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("""

,id,doc_id,chunk_index,text,embedding,symbol,year,quarter,date,source,text_search
0,1,AAPL_2026Q3,0,"Suhasini Chandramouli: Good afternoon, welcome...","[-0.0763495,0.019191494,0.02197783,-0.00140912...",AAPL,2026,3,2026-07-30,roic.ai,"'10':178B,182B,210B '2026':2A,15B,218B '27':21..."
1,2,AAPL_2026Q3,1,"the quarter ended June 27, 2026, to be filed ...","[-0.02154462,-0.0131144775,0.04783241,-0.02665...",AAPL,2026,3,2026-07-30,roic.ai,"'109.4':79B '16':84B '2026':2A,9B '22':125B '2..."
2,3,AAPL_2026Q3,2,t growth in most emerging markets. This year's...,"[-0.11674006,-0.04834747,-0.0036011648,-0.0233...",AAPL,2026,3,2026-07-30,roic.ai,'2026':2A '3':3A 'aapl':1A 'absolut':55B 'acad...
3,4,AAPL_2026Q3,3,goal is to make it easier for parents to manag...,"[-0.04078931,0.010441453,0.06402649,-0.0647822...",AAPL,2026,3,2026-07-30,roic.ai,"'10.4':219B '17':177B,196B '17e':203B '2026':2..."
4,5,AAPL_2026Q3,4,a year ago despite significant supply constra...,"[0.003532718,-0.06113888,0.057587687,-0.008391...",AAPL,2026,3,2026-07-30,roic.ai,'2026':2A '3':3A 'aapl':1A 'accord':34B 'achie...
...,...,...,...,...,...,...,...,...,...,...,...
258,206,TSLA_2026Q2,34,"got a better one, I'd like to need that perso...","[-0.08943219,-0.008513211,0.00671214,-0.000850...",TSLA,2026,2,2026-07-22,roic.ai,"'2':3A '2026':2A 'actual':191B,286B 'ai':21B '..."
259,207,TSLA_2026Q2,35,ciency versus time. So if we can be -- it's ok...,"[-0.022584891,-0.057968706,-0.022716844,-0.033...",TSLA,2026,2,2026-07-22,roic.ai,'2':3A '2026':2A 'actual':31B 'add':145B 'ahea...
260,208,TSLA_2026Q2,36,"turing, which happens in the U.S., we are just...","[-0.07462848,-0.016487533,-0.00094480143,0.041...",TSLA,2026,2,2026-07-22,roic.ai,"'2':3A '2026':2A 'address':194B,244B 'advantag..."
261,209,TSLA_2026Q2,37,en the sharp fluctuations in power use where y...,"[-0.049953196,-0.012333106,0.0658104,0.0750279...",TSLA,2026,2,2026-07-22,roic.ai,'100':236B '2':3A '2026':2A '70':234B 'abl':25...
262,210,TSLA_2026Q2,38,00 milliseconds. And you really need fast-acti...,"[-0.0066875545,0.0039739716,0.029370958,0.0699...",TSLA,2026,2,2026-07-22,roic.ai,'0.5':163B '00':4B '1.2':146B '1.3':148B '2':3...

In [5]:
load_dotenv()
conn_str = os.getenv("PG_CONN_STR")

## below was used to create a new column text_search
no longer in used

In [6]:
sql = """
ALTER TABLE earnings_chunks
ADD COLUMN IF NOT EXISTS text_search tsvector;
"""
with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        cur.execute(sql)

In [7]:
sql = """
UPDATE earnings_chunks
SET text_search = to_tsvector('english', text);
"""
with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        cur.execute(sql)

In [8]:
sql = """
CREATE INDEX IF NOT EXISTS earnings_chunks_text_search_idx
ON earnings_chunks
USING GIN (text_search);
"""
with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        cur.execute(sql)

In [ ]:
# fix later ingested ticker doesn't have text_search populated
import os
import pandas as pd
import psycopg
from dotenv import load_dotenv
conn = psycopg.connect(os.environ["PG_CONN_STR"])

conn.execute("""
    UPDATE earnings_chunks
    SET text_search =
        setweight(
            to_tsvector(
                'simple',
                coalesce(symbol, '') || ' ' ||
                coalesce(year::text, '') || ' ' ||
                coalesce(quarter::text, '')
            ),
            'A'
        )
        ||
        setweight(
            to_tsvector('english', coalesce(text, '')),
            'B'
        )
    WHERE text_search IS NULL
""")

conn.commit()
conn.close()

In [14]:
# inspect the new column and index
import os
import pandas as pd
import psycopg
from dotenv import load_dotenv

load_dotenv()

with psycopg.connect(os.environ["PG_CONN_STR"]) as conn:
    with conn.cursor() as cur:
        cur.execute("""
            SELECT id, doc_id, chunk_index, symbol, year, quarter, date, source, text, text_search
            FROM earnings_chunks
            ORDER BY symbol, year, quarter, chunk_index
        """)
        rows = cur.fetchall()
        cols = [desc[0] for desc in cur.description]

df = pd.DataFrame(rows, columns=cols)
df.head(20)

,id,doc_id,chunk_index,symbol,year,quarter,date,source,text,text_search
0,119,AAPL_2026Q3,0,AAPL,2026,3,2026-07-30,roic.ai,"Suhasini Chandramouli: Good afternoon, welcome...",'2026':12 'actual':118 'afternoon':4 'also':44...
1,120,AAPL_2026Q3,1,AAPL,2026,3,2026-07-30,roic.ai,e potential impact to the company's business a...,"'10':44,48,76 '109.4':154 '16':159 '2026':84 '..."
2,121,AAPL_2026Q3,2,AAPL,2026,3,2026-07-30,roic.ai,"eased to report $109.4 billion in revenue, up ...",'109.4':4 '16':9 '22':50 '29':78 '30.7':94 'ab...
3,122,AAPL_2026Q3,3,AAPL,2026,3,2026-07-30,roic.ai,developed and emerging markets and saw double-...,"'absolut':60 'across':54 'ai':38,72,111 'all-n..."
4,123,AAPL_2026Q3,4,AAPL,2026,3,2026-07-30,roic.ai,"excited about it, we are feeling incredibly e...",'22':151 '54.3':148 'academi':75 'achiev':157 ...
5,124,AAPL_2026Q3,5,AAPL,2026,3,2026-07-30,roic.ai,iPhone revenue for the June quarter was $54.3...,"'10.4':154 '17':112,131 '17e':138 '22':11 '29'..."
6,125,AAPL_2026Q3,6,AAPL,2026,3,2026-07-30,roic.ai,ac delivered its best June quarter yet with $1...,'10.4':9 '29':16 'ac':1 'accord':48 'achiev':9...
7,126,AAPL_2026Q3,7,AAPL,2026,3,2026-07-30,roic.ai,d creation across a broad range of AI workload...,"'6.2':131 'across':3,44 'agent':29 'ai':8,30,1..."
8,127,AAPL_2026Q3,8,AAPL,2026,3,2026-07-30,roic.ai,"the ultimate go-anywhere, do anything device ...",'6':96 '7.9':93 'accessori':91 'achiev':108 'a...
9,128,AAPL_2026Q3,9,AAPL,2026,3,2026-07-30,roic.ai,had. We're delivering useful features backed b...,"'2':84 '3':70 'across':56,132 'activ':78 'ai':..."
10,129,AAPL_2026Q3,10,AAPL,2026,3,2026-07-30,roic.ai,"es are intuitive and useful, while also deeply...","'2017':55 'advanc':157 'ai':47,75,129,136 'als..."
11,130,AAPL_2026Q3,11,AAPL,2026,3,2026-07-30,roic.ai,That's why developers and researchers are incr...,'12':34 '30.7':25 '89':155 'ad':116 'advanc':1...
12,131,AAPL_2026Q3,12,AAPL,2026,3,2026-07-30,roic.ai,"is year's Emmy Awards, where Apple has landed ...",'170':92 '19':53 '3':75 '800':76 '850':71 '89'...
13,132,AAPL_2026Q3,13,AAPL,2026,3,2026-07-30,roic.ai,"teams. In retail, we were pleased to announce ...","'access':105,136 'across':74 'ad':166 'also':1..."
14,133,AAPL_2026Q3,14,AAPL,2026,3,2026-07-30,roic.ai,re also using on-device speech recognition to ...,"'600':91 'ad':21 'advanc':129 'agreement':141,..."
15,134,AAPL_2026Q3,15,AAPL,2026,3,2026-07-30,roic.ai,n components and cutting-edge wireless connect...,"'30':31 'advanc':77,93,147 'agreement':15 'ahe..."
16,135,AAPL_2026Q3,16,AAPL,2026,3,2026-07-30,roic.ai,ntire advanced manufacturing ecosystem. We hav...,'109.4':147 '16':151 'advanc':2 'afternoon':13...
17,136,AAPL_2026Q3,17,AAPL,2026,3,2026-07-30,roic.ai,"r-over-year, a June quarter revenue record. We...",'12':91 '140':169 '18':35 '30.7':88 '40.1':167...
18,137,AAPL_2026Q3,18,AAPL,2026,3,2026-07-30,roic.ai,"ve this favorable impact, we would have been a...",'0.11':108 '110':61 '140':26 '17':169 '19.1':7...
19,138,AAPL_2026Q3,19,AAPL,2026,3,2026-07-30,roic.ai,tails for each of our revenue categories. iPho...,"'10.4':121 '17':23,103 '22':14 '29':124 '451':..."

In [3]:
import os

os.environ["HF_HUB_OFFLINE"] = "1"

# text index.py after changing chunk size

In [2]:
from src.index import text_search, vector_search, hybrid_search

query = "what did apple say about revenue?"

text_results = text_search(query, limit=5)
vector_results = vector_search(query, limit=5)
hybrid_results = hybrid_search(query, limit=5)

for name, results in [
    ("TEXT", text_results),
    ("VECTOR", vector_results),
    ("HYBRID", hybrid_results),
]:
    print(f"\n=== {name} ===")
    for r in results:
        print(r["symbol"], r["year"], r["quarter"], r.get("score"), r["text"][:200])

=== TEXT ===
AAPL 2026 3 0.34344503  combination of massive unified memory bandwidth, industry-leading power-efficient performance, and deep on-device intelligence, all built around the customer experience from the ground up. The result
AAPL 2026 3 0.33098254 tory proceedings. For more information, please refer to the risk factors discussed in Apple's most recently filed reports on Form 10-Q and Form 10-K, and the Form 8-K filed with the SEC today, along w
AAPL 2026 3 0.30396354 ith strong double-digit growth in markets like Latin America, India, and Southeast Asia. The customer reception to MacBook Neo has been incredible. We continue to attract new customers to the product
AAPL 2026 3 0.30396354 hanges to the App Store business model in certain countries. In the U.S., we do continue to operate under a court ruling impacting the link-out transactions. We're pleased the Supreme Court will hear
AAPL 2026 3 0.2995392 ing markets. The wearables install base reached a new all-time high. We set a June quarter record for upgraders on Apple Watch, and over half the customers purchasing an Apple Watch during the quarter

=== VECTOR ===
AAPL 2026 3 0.6739249229431152 t $34.4 billion. All three of these metrics set June quarter records, even when excluding the tariff refund benefit. I'm going to provide some more details for each of our revenue categories. iPhone r
AAPL 2026 3 0.6341937780380249 ith strong double-digit growth in markets like Latin America, India, and Southeast Asia. The customer reception to MacBook Neo has been incredible. We continue to attract new customers to the product
AAPL 2026 3 0.6220147609710693 tory proceedings. For more information, please refer to the risk factors discussed in Apple's most recently filed reports on Form 10-Q and Form 10-K, and the Form 8-K filed with the SEC today, along w
AAPL 2026 3 0.6074767889820575 hanges to the App Store business model in certain countries. In the U.S., we do continue to operate under a court ruling impacting the link-out transactions. We're pleased the Supreme Court will hear
AAPL 2026 3 0.5965324995835136 rom the June quarter to the September quarter. Second, we expect the impact from supply constraints to increase significantly sequentially. The projected supply constraints in the September quarter af

=== HYBRID ===
AAPL 2026 3 0.33098254 tory proceedings. For more information, please refer to the risk factors discussed in Apple's most recently filed reports on Form 10-Q and Form 10-K, and the Form 8-K filed with the SEC today, along w
AAPL 2026 3 0.30396354 ith strong double-digit growth in markets like Latin America, India, and Southeast Asia. The customer reception to MacBook Neo has been incredible. We continue to attract new customers to the product
AAPL 2026 3 0.30396354 hanges to the App Store business model in certain countries. In the U.S., we do continue to operate under a court ruling impacting the link-out transactions. We're pleased the Supreme Court will hear
AAPL 2026 3 0.34344503  combination of massive unified memory bandwidth, industry-leading power-efficient performance, and deep on-device intelligence, all built around the customer experience from the ground up. The result
AAPL 2026 3 0.6739249229431152 t $34.4 billion. All three of these metrics set June quarter records, even when excluding the tariff refund benefit. I'm going to provide some more details for each of our revenue categories. iPhone r

# test index.py

In [ ]:
# test index.py
from src.index import text_search, vector_search, hybrid_search

query = "what did apple say about revenue?"

text_results = text_search(query, limit=5)
vector_results = vector_search(query, limit=5)
hybrid_results = hybrid_search(query, limit=5)


for name, results in [
    ("TEXT", text_results),
    ("VECTOR", vector_results),
    ("HYBRID", hybrid_results),
]:
    print(f"\n=== {name} ===")
    for r in results:
        print(r["symbol"], r["year"], r["quarter"], r.get("score"), r["text"][:200])

=== TEXT ===
AAPL 2026 3 0.33858162 That's why developers and researchers are increasingly using Apple devices to build ever more advanced tools and models. Turning to services, revenue was $30.7 billion, a June quarter revenue record a
AAPL 2026 3 0.32993555 ssories revenue was $7.9 billion, up 6% year-over-year, driven by strength in wearables and accessories, and we saw growth in both developed and emerging markets. The wearables install base reached a
AAPL 2026 3 0.30396354 under a court ruling impacting the link-out transactions. We're pleased the Supreme Court will hear our appeal. Despite this, the App Store did set a June quarter revenue record. We take a step back.
AAPL 2026 3 0.29467577 ac delivered its best June quarter yet with $10.4 billion in revenue, growing an impressive 29% from a year ago despite significant supply constraints. This revenue growth was driven by the incredible
AAPL 2026 3 0.29467577 es are intuitive and useful, while also deeply integrated in a way that's personal and private with the latest models running on-device and on servers using private cloud compute. We began laying the

=== VECTOR ===
AAPL 2026 3 0.6701093912124634 tails for each of our revenue categories. iPhone revenue was $54.3 billion, up 22% year-over-year, driven by the iPhone 17 family. We grew double digits in the vast majority of markets we track and re
AAPL 2026 3 0.6543986797332764 under a court ruling impacting the link-out transactions. We're pleased the Supreme Court will hear our appeal. Despite this, the App Store did set a June quarter revenue record. We take a step back.
AAPL 2026 3 0.6011936068534851 eased to report $109.4 billion in revenue, up 16% from a year ago and a June quarter record. We were able to achieve this despite supply constraints and sequential foreign exchange headwinds. We conti
AAPL 2026 3 0.5923692098104054  iPhone revenue for the June quarter was $54.3 billion, up 22% from a year ago. We achieved June quarter records in every geographic segment and set a June quarter record for upgraders. According to I
AAPL 2026 3 0.5485964686515061 ttle bit about the expected adoption rates across your two and a half billion device install base in success? Do you see it shortening the replacement cycle for iPhone or also having an equal impact t

=== HYBRID ===
AAPL 2026 3 0.30396354 under a court ruling impacting the link-out transactions. We're pleased the Supreme Court will hear our appeal. Despite this, the App Store did set a June quarter revenue record. We take a step back.
AAPL 2026 3 0.33858162 That's why developers and researchers are increasingly using Apple devices to build ever more advanced tools and models. Turning to services, revenue was $30.7 billion, a June quarter revenue record a
AAPL 2026 3 0.6701093912124634 tails for each of our revenue categories. iPhone revenue was $54.3 billion, up 22% year-over-year, driven by the iPhone 17 family. We grew double digits in the vast majority of markets we track and re
AAPL 2026 3 0.32993555 ssories revenue was $7.9 billion, up 6% year-over-year, driven by strength in wearables and accessories, and we saw growth in both developed and emerging markets. The wearables install base reached a
AAPL 2026 3 0.6011936068534851 eased to report $109.4 billion in revenue, up 16% from a year ago and a June quarter record. We were able to achieve this despite supply constraints and sequential foreign exchange headwinds. We conti

In [ ]:
from src.index import _connect

query = "what did apple say about revenue?"

with _connect() as conn:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT websearch_to_tsquery('english', %s)::text",
            (query,)
        )
        result = cur.fetchone()[0]

result

"'appl' & 'say' & 'revenu'"

In [15]:
with _connect() as conn:
    with conn.cursor() as cur:
        cur.execute("""
            SELECT count(*)
            FROM earnings_chunks
            WHERE text_search @@ to_tsquery('english', 'revenu')
        """)
        count = cur.fetchone()[0]

count

83

In [20]:
with _connect() as conn:
    with conn.cursor() as cur:
        cur.execute("""
            SELECT count(*)
            FROM earnings_chunks
            WHERE text_search @@ websearch_to_tsquery('english', 'apple revenue')
        """)
        count = cur.fetchone()[0]

count

10

In [3]:
import os
from dotenv import load_dotenv

load_dotenv()
os.getenv("PG_CONN_STR")

'postgresql://raguser:ragpass@localhost:5432/ragdb'

# # test index.py with rewriting

In [ ]:
# test index.py
from src.index_rewrite import text_search, vector_search, hybrid_search
query = "What did google say about AI infrastructure and expenses"

text_results = text_search(query, limit=5)
vector_results = vector_search(query, limit=5)
hybrid_results = hybrid_search(query, limit=5)

for name, results in [
    ("TEXT", text_results),
    ("VECTOR", vector_results),
    ("HYBRID", hybrid_results),
]:
    print(f"\n=== {name} ===")
    for r in results:
        print(
            r["symbol"],
            r["year"],
            r["quarter"],
            r.get("score"),
            r.get("rrf_score"),
            r["text"][:200].replace("\n", " "),
        )

Normalized query for text search: google or ai or infrastructure or expenses
Normalized query for text search: google or ai or infrastructure or expenses

=== TEXT ===
GOOG 2026 2 4.4 None hose who adopt our AI-powered campaigns like AI Max or PMax see an average of 15% more conversions or value on search at a similar ROAS. AAA Auto Club enterprises used AI Max to personalize creative a
GOOG 2026 2 3.6000001 None th Search. AI continues to drive an expansionary moment with new experiences resonating with users and driving growth inquiries. As a big football fan, I was particularly excited to see Search usage h
META 2026 2 3.2 None over-year, driven primarily by WhatsApp paid messaging and subscriptions revenue. Within our Reality Labs segment, Q2 revenue was $431 million, up 16% year-over-year due to strong growth in AI glasses
GOOG 2026 2 3.2 None e including financial services organizations such as Morgan Stanley, telecommunication providers such as TELUS, health care organizations such as Texas Children's, software companies such as Atlassian
GOOG 2026 2 3.2 None  revenues of $7.3 billion were down 1%. Subscription platforms and devices revenues increased 15% this quarter to $12.9 billion due to strong growth in both YouTube subscriptions, particularly YouTube

=== VECTOR ===
META 2026 2 0.6167291631264005 None ne the ability to direct it towards what matters to them. That's the way that society has always made progress. I think that these are the right values for building a positive AI future. And if we hel
META 2026 2 0.5644676944930745 None  long-duration sources of capital as we make investments in initiatives that themselves have long time horizons, especially AI infrastructure projects. We've also broadened our aperture there to inclu
META 2026 2 0.5443104181104659 None . So I encourage you to tune in then. Before I wrap, I want to mention that I just published an op-ed about why I'm so optimistic that we are building a positive future for everyone. At Meta, we have
INTC 2026 2 0.5392093062400857 None r the last 4 quarters, underpinning that manageability and enhanced security are critical must-haves in the agentic workplace. We expect enterprise adoption of AI to be a long-term tailwind for CCPG,
META 2026 2 0.4943959123616324 None AI for everyone, how do you think about whether consumer adoption can close this AI utility gap? Like are we on the cusp of something kind of breaking through? Or do we just need to be a bit more pati

=== HYBRID ===
META 2026 2 2.4 0.031054405392392875  long-duration sources of capital as we make investments in initiatives that themselves have long time horizons, especially AI infrastructure projects. We've also broadened our aperture there to inclu
GOOG 2026 2 4.4 0.01639344262295082 hose who adopt our AI-powered campaigns like AI Max or PMax see an average of 15% more conversions or value on search at a similar ROAS. AAA Auto Club enterprises used AI Max to personalize creative a
META 2026 2 0.6167291631264005 0.01639344262295082 ne the ability to direct it towards what matters to them. That's the way that society has always made progress. I think that these are the right values for building a positive AI future. And if we hel
GOOG 2026 2 3.6000001 0.016129032258064516 th Search. AI continues to drive an expansionary moment with new experiences resonating with users and driving growth inquiries. As a big football fan, I was particularly excited to see Search usage h
META 2026 2 3.2 0.015873015873015872 over-year, driven primarily by WhatsApp paid messaging and subscriptions revenue. Within our Reality Labs segment, Q2 revenue was $431 million, up 16% year-over-year due to strong growth in AI glasses

# text index_rewrite.py after changing chunk size

In [3]:
# test index.py
from src.index_rewrite import text_search, vector_search, hybrid_search
query = "What did google say about AI infrastructure and expenses"

text_results = text_search(query, limit=5)
vector_results = vector_search(query, limit=5)
hybrid_results = hybrid_search(query, limit=5)

for name, results in [
    ("TEXT", text_results),
    ("VECTOR", vector_results),
    ("HYBRID", hybrid_results),
]:
    print(f"\n=== {name} ===")
    for r in results:
        print(
            r["symbol"],
            r["year"],
            r["quarter"],
            r.get("score"),
            r.get("rrf_score"),
            r["text"][:200].replace("\n", " "),
        )

Normalized query for text search: google or ai or infrastructure or expenses
Normalized query for text search: google or ai or infrastructure or expenses

=== TEXT ===
GOOG 2026 2 4.8 None d monitoring. Today, 90% of Fortune 100 are Google Cloud security users. Nearly 90% of this customers are using AI-powered security features. And we have seen a more than 45% quarter-over-quarter incr
GOOG 2026 2 3.6000001 None . A reconciliation of non-GAAP to GAAP measures is included in today's earnings press release, which is distributed and available to the public through our Investor Relations website located at abc.xy
GOOG 2026 2 3.6000001 None m in Chrome is now on track to accelerate delivery by 8 times compressing a 2-year time line into 3 months through model-driven refactoring. Moving on to our global product footprint, which brings AI
GOOG 2026 2 3.6000001 None e AI creative tools, which makes creative development easier, especially for SMBs. In fact, over half of our SMB customers globally use AI to create or optimize their creative. Third, new AI user expe
GOOG 2026 2 3.6000001 None s well as brand with strength in the living room, as Phillipp mentioned earlier. Network advertising revenues of $7.3 billion were down 1%. Subscription platforms and devices revenues increased 15% th

=== VECTOR ===
MSFT 2026 4 0.574830710887913 None continued investments in AI infrastructure and growing product usage, partially offset by ongoing efficiency gains, particularly in Azure and M365 Commercial cloud. Operating expenses increased 10%, d
META 2026 2 0.5584400226545306 None e progress. I think that these are the right values for building a positive AI future. And if we help build this, then I think that we will continue to build a very strong business as well. So that's
GOOG 2026 2 0.53703722136991 None gress from our other bets. Waymo introduced its newest vehicle or high to public riders. This is the first vehicle powered by the sixth generation Waymo Driver and we'll welcome more riders in the com
GOOG 2026 2 0.5277836322784462 None me mention 3 unique offerings. First, our VIrgo network, which is designed to meet the needs of modern large-scale AI workloads. It allows customers to connect 1 million AI acirators across multiple d
META 2026 2 0.5267712316879284 None sing that to be able to further add intelligence and improve the ranking and recommendations and ads in the core services. So I think all of that is true. And it creates this dynamic where there is a

=== HYBRID ===
MSFT 2026 4 2.8 0.03131881575727918 continued investments in AI infrastructure and growing product usage, partially offset by ongoing efficiency gains, particularly in Azure and M365 Commercial cloud. Operating expenses increased 10%, d
GOOG 2026 2 3.6000001 0.031024531024531024 m in Chrome is now on track to accelerate delivery by 8 times compressing a 2-year time line into 3 months through model-driven refactoring. Moving on to our global product footprint, which brings AI
GOOG 2026 2 2.4 0.0293236301369863 me mention 3 unique offerings. First, our VIrgo network, which is designed to meet the needs of modern large-scale AI workloads. It allows customers to connect 1 million AI acirators across multiple d
GOOG 2026 2 2.4 0.028814262023217248 re using Gemini Enterprise. We have customers like PepsiCo for AI and analytics solutions, Intel to streamline core processes, HSBC for wealth management, Bell Canada for customer engagement, Macy's f
AAPL 2026 3 2.4 0.02877846790890269 u're asking is true. Obviously, we've now had to increase prices on iPad and Mac, the price elasticity there, it's just too early to come to a definitive conclusion of what happens there. Because it t

# test rag_helper_project

In [11]:
from src.rag_helper_project import ask

result = ask("What did Apple say about revenue?")
print(result["answer"])

Apple reported total revenue of $109.4 billion, up 16% from a year ago, marking a June quarter record.

Key revenue figures and records include:
*   **Services revenue** was $30.7 billion, a June quarter record and up 12% year-over-year. Within Services, June quarter revenue records were set in advertising, the App Store, AppleCare, music, and video, with all-time records in cloud services and payment services. Services also achieved an all-time revenue record in developed markets and a June quarter record in emerging markets.
*   **iPhone revenue** was $54.3 billion, up 22% year-over-year, a June quarter record, with records across both developed and emerging markets.
*   **Mac revenue** was $10.4 billion, up 29% year-over-year, a new June quarter record.
*   **Accessories revenue** was $7.9 billion, up 6% year-over-year.

June quarter revenue records were achieved in every geographic segment, including the U.S., Latin America, Western Europe, India, China Mainland, Japan, and Southeast Asia, as well as in both developed and emerging markets.

# # test rag_helper_project after chaging chunk size 1200, 200

In [4]:
from src.rag_helper_project import ask

result = ask("What did Apple say about revenue?")
print(result["answer"])

Warning: there are non-text parts in the response: ['thought_signature'], returning concatenated text result from text parts. Check the full candidates.content.parts accessor to get the full model response.
Warning: there are non-text parts in the response: ['thought_signature'], returning concatenated text result from text parts. Check the full candidates.content.parts accessor to get the full model response.

Based on the transcript for the June quarter (Q3 2026), Apple reported the following details regarding revenue:

* **Total Revenue:** $109.4 billion, up 16% year-over-year, setting a June quarter record despite supply constraints and sequential foreign exchange headwinds.
* **iPhone Revenue:** $54.3 billion, up 22% year-over-year to a June quarter record, driven by strong demand for the iPhone 17 family across developed and emerging markets.
* **Mac Revenue:** $10.4 billion, up 29% year-over-year to a June quarter record, driven by strength in the MacBook Neo and MacBook Pro.
* **Services Revenue:** $30.7 billion, up 12% year-over-year to a June quarter record (and an all-time record in developed markets), driven by strong double-digit growth in cloud services, video, payment services, and advertising.
* **Wearables, Home, and Accessories Revenue:** $7.9 billion, up 6% year-over-year, driven by strength in wearables and accessories across both developed and emerging markets.
* **iPad Revenue:** $6.2 billion, down 6% year-over-year, driven by a difficult comparison against the prior year's launch of the A16-powered iPad.

In [4]:
result = ask("How is Meta planning its AI capacity investments for 2026 and 2027?")
print(result["answer"])

Warning: there are non-text parts in the response: ['thought_signature'], returning concatenated text result from text parts. Check the full candidates.content.parts accessor to get the full model response.
Warning: there are non-text parts in the response: ['thought_signature'], returning concatenated text result from text parts. Check the full candidates.content.parts accessor to get the full model response.

Based on the provided transcript, Meta is gearing its current infrastructure plans toward maximizing capacity in 2026 and 2027.

Key details and drivers of this strategy include:

* **Valuation of Near-Term Capacity:** Meta believes near-term capacity is more valuable than long-term capacity because the industry has historically underbuilt for the wave of AI adoption, and industry capacity is expected to remain tight.
* **Core Drivers:** Meta has high confidence in utilizing this capacity to scale and build on existing experiences (drawing parallels to how past capacity helped scale Reels), continue investing in foundational models, and capture new product opportunities.
* **Flexibility for 2028 and Beyond:** Maximizing 2026 and 2027 capacity helps lay the data center and network foundations needed to provide flexibility to grow compute in 2028 and beyond, allowing Meta to adjust server decisions based on actual needs and the pace of AI adoption.
* **Specific Guidance:** Meta is not providing a specific CapEx outlook figure for 2027 at this time, noting that infrastructure planning remains highly dynamic.

# test rag_helper_project_rewrite

In [ ]:
from src.rag_helper_project_rewrite import ask

result = ask("How is Meta planning its AI capacity investments for 2026 and 2027?")
print(result["answer"])

Query rewriting failed: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.6-flash\nPlease retry in 6.180336014s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.6-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '6s'}]}}. Using original query.

=== QUERY REWRITE ===
Original query:   How is Meta planning its AI capacity investments for 2026 and 2027?
Search query:     How is Meta planning its AI capacity investments for 2026 and 2027?
Symbols:          []
Year:             None
Quarter:          None
Normalized query for text search: how or meta or planning or its or ai or capacity or investments or for or 2026 or 2027

=== RETRIEVED CONTEXT ===
[1] META 2026 Q2
AI for everyone, how do you think about whether consumer adoption can close this AI utility gap? Like are we on the cusp of something kind of breaking through? Or do we just need to be a bit more patient?

Mark Zuckerberg : Well, I think that some things have already broken through. And I think one of the interesting things about AI compared to other technologies is that every year or so and the cycle may accelerate, but every year or so, you get new capabilities that create new possible product lines. So there's obviously the AI assistant market for consumers where that's what we're doing with Meta AI and then there's the other products that competitors have in that space. And then in the last year, I think the coding agent market has really grown very quickly. And that's the first real agentic market. And I think that there's a number of reasons why coding is first, right? You have technical customers who are willing to do the work to make it work. Coding is an inher

Warning: there are non-text parts in the response: ['thought_signature'], returning concatenated text result from text parts. Check the full candidates.content.parts accessor to get the full model response.
Warning: there are non-text parts in the response: ['thought_signature'], returning concatenated text result from text parts. Check the full candidates.content.parts accessor to get the full model response.

Meta's current plans are geared towards maximizing its 2026 and 2027 AI capacity.

Key drivers and context behind this planning include:
* **Industry Underbuilding and Supply Chains:** The industry has historically underbuilt for AI adoption, making capacity extremely valuable, while longer-term supply chains need to be built out to support anticipated needs for AI-powered experiences.
* **Capacity Utilization:** Meta has high confidence in its ability to utilize capacity to scale and build on top of existing experiences, as well as continue investing in foundational models to create new opportunities.
* **Historical Precedent:** Meta is confident in this strategy because incremental capacity in the past proved extremely valuable when scaling experiences like Reels.

# test rag_helper_project_rewrite after changing chunk size

In [2]:
from src.rag_helper_project_rewrite import ask

result = ask("How is Meta planning its AI capacity investments for 2026 and 2027?")
print(result["answer"])

Warning: there are non-text parts in the response: ['thought_signature'], returning concatenated parsed result from text parts. Check the full candidates.content.parts accessor to get the full model response.

=== RAW QUERY REWRITE RESPONSE ===
'{"search_query":"Meta META AI capacity investments capex infrastructure 2026 2027 planning guidance","symbols":["META"],"year":null,"quarter":null}'

=== QUERY REWRITE ===
Original query:   How is Meta planning its AI capacity investments for 2026 and 2027?
Search query:     Meta META AI capacity investments capex infrastructure 2026 2027 planning guidance
Symbols:          ['META']
Year:             None
Quarter:          None
Normalized query for text search: meta or meta or ai or capacity or investments or capex or infrastructure or 2026 or 2027 or planning or guidance

=== RETRIEVED CONTEXT ===
[1] META 2026 Q2
apacity that we anticipate we and others will need for AI-powered experiences. Second, we have high confidence in our ability to utilize capacity to scale and build on top of our existing experiences as well as continue to invest in foundational models that will create substantial new opportunities. Consequently, our current plans are geared towards maximizing 2026 and 2027 capacity. When we have had incremental capacity in the past, it has proven extremely valuable in scaling experiences like Reels, and we are confident that this will be true in this time frame as well. Longer term, it's harder to predict the exact usage scaling curves, but we believe that our distribution advantages will give us the opportunity to serve AI products that are valuable for everyone, both our 3.6 billion users and millions of businesses. This should be true regardless of whether our models are on the frontier, but we believe that being on the frontier will unlock new markets and opportun

=== RETRIEVED CONTEXT END===

Warning: there are non-text parts in the response: ['thought_signature'], returning concatenated text result from text parts. Check the full candidates.content.parts accessor to get the full model response.
Warning: there are non-text parts in the response: ['thought_signature'], returning concatenated text result from text parts. Check the full candidates.content.parts accessor to get the full model response.

Based on the provided transcript context, Meta is gearing its current infrastructure plans toward **maximizing capacity in 2026 and 2027**, operating under the belief that near-term capacity is currently more valuable than long-term capacity.

Key details and drivers for this strategy include:
* **Key Drivers:** High confidence in Meta's ability to utilize capacity to scale and build on top of existing experiences (such as Reels) and to continue investing in foundational models to unlock substantial new opportunities.
* **CapEx Outlook:** Meta is not providing a specific CapEx outlook for 2027 at this time, as infrastructure planning remains highly dynamic.
* **Longer-term Flexibility:** Maximizing capacity in 2026 and 2027 by laying down data center and network foundations is also designed to give Meta the flexibility to continue growing compute in 2028 and beyond.